import React,{useEffect,useState}from'react';
import{GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut,User}from'firebase/auth';
import{auth}from'../firebase';
import{LogIn,Loader2,ShieldCheck,LogOut}from'lucide-react';

export default function AuthGate({children}:{children:React.ReactNode}){
 const[user,setUser]=useState<User|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setLoading(false)}),[]);
 useEffect(()=>{if(!user)return;const original=window.fetch;window.fetch=async(input:any,init:any={})=>{const url=typeof input==='string'?input:input?.url||'';if(url.includes('/api/recruiting/')||url.includes('/api/control-plane/')){const token=await user.getIdToken();const headers=new Headers(init.headers||{});headers.set('Authorization',`Bearer ${token}`);return original(input,{...init,headers})}return original(input,init)};return()=>{window.fetch=original}},[user]);
 async function login(){setBusy(true);setError('');try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(e:any){setError(e?.message||'Google sign-in failed')}finally{setBusy(false)}}
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-50"><Loader2 className="h-7 w-7 animate-spin text-violet-600"/></div>;
 if(!user)return <div className="flex min-h-screen items-center justify-center bg-slate-50 p-5"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 text-center shadow-xl sm:p-9"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-violet-600 text-white"><ShieldCheck className="h-7 w-7"/></div><h1 className="mt-6 text-2xl font-black tracking-tight">Sign in to Smart Scout</h1><p className="mt-2 text-sm leading-6 text-slate-500">Your hiring workspace is private. Sign in to create jobs, manage candidates and access hiring decisions.</p><button onClick={login} disabled={busy} className="mt-7 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-3.5 text-sm font-black text-white disabled:opacity-60"><LogIn className="h-4 w-4"/>{busy?'Signing in…':'Continue with Google'}</button>{error&&<p className="mt-4 text-xs text-rose-600">{error}</p>}<p className="mt-6 text-[11px] text-slate-400">Smart Scout uses Firebase Authentication for account identity.</p></div></div>;
 return <div className="relative"><div className="sticky top-0 z-40 flex justify-end border-b border-slate-200 bg-white/95 px-3 py-2 backdrop-blur sm:px-6"><div className="flex items-center gap-2 text-xs font-semibold text-slate-500"><span className="hidden sm:inline">{user.email||user.displayName||'Signed in'}</span><button onClick={()=>signOut(auth)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 font-bold"><LogOut className="h-3.5 w-3.5"/>Sign out</button></div></div>{children}</div>;
}
