import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,ArrowLeft,Check,ChevronRight,KeyRound,Loader2,Mic,Send,ShieldCheck,Sparkles,X}from'lucide-react';

type A={title?:string;description?:string;mustHave?:string[];niceToHave?:string[];location?:string;experienceMin?:number;experienceMax?:number;compensationMin?:number;compensationMax?:number;department?:string;competencies?:string[];interviewFocus?:string[]};
type C={id?:string;name:string;headline?:string;location?:string;profileUrl?:string;summary?:string;evidence?:string[];score?:any};
const H={'content-type':'application/json','x-tenant-id':'demo-tenant'};
async function api(p:string,b?:any,m='POST'){const r=await fetch(`/api/recruiting/${p}`,{method:m,headers:H,body:m==='GET'?undefined:JSON.stringify(b||{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
async function control(p:string,b?:any,m='POST'){const r=await fetch(`/api/control-plane/${p}`,{method:m,headers:H,body:m==='GET'?undefined:JSON.stringify(b||{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Control-plane request failed');return d}
const STEPS=['intent','job','source','screen','interview','decision','comp','offer','engagement','onboarding'];
const ACTION_LABEL:{[k:string]:string}={jd_approval:'JD',decision:'decision',compensation:'compensation',offer:'offer'};
export default function HiringLifecycleV3({onBack}:{onBack?:()=>void}){
 const[stage,setStage]=useState('intent'),[prompt,setPrompt]=useState(''),[jobId,setJobId]=useState(''),[analysis,setAnalysis]=useState<A|null>(null),[title,setTitle]=useState(''),[jd,setJd]=useState(''),[candidates,setCandidates]=useState<C[]>([]),[selected,setSelected]=useState<C|null>(null),[questions,setQuestions]=useState<any[]>([]),[answers,setAnswers]=useState<string[]>([]),[interviewId,setInterviewId]=useState(''),[decision,setDecision]=useState<any>(),[comp,setComp]=useState<any>(),[offer,setOffer]=useState<any>(),[engagement,setEngagement]=useState<any[]>([]),[onboarding,setOnboarding]=useState<any>(),[approval,setApproval]=useState<any>(null),[approvals,setApprovals]=useState<any[]>([]),[connected,setConnected]=useState(false),[provider,setProvider]=useState('gemini'),[apiKey,setApiKey]=useState(''),[showKey,setShowKey]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[listening,setListening]=useState(false);
 const fail=(e:any)=>setError(e?.message||'Something went wrong');
 useEffect(()=>{api('ai/status',undefined,'GET').then((d:any)=>{setConnected(Boolean(d.connected));setProvider(d.provider||'gemini')}).catch(()=>{})},[]);
 async function refreshApprovals(id=jobId){if(!id)return;try{const d=await control(`approvals?jobId=${encodeURIComponent(id)}`,undefined,'GET');setApprovals(d.approvals||[]);return d.approvals||[]}catch{return[]}}
 useEffect(()=>{if(jobId)refreshApprovals()},[jobId]);
 const quality=useMemo(()=>{const text=[prompt,jd,analysis?.description||'',...(analysis?.mustHave||[]),...(analysis?.niceToHave||[])].join(' ').toLowerCase();const proxy=['young','energetic','digital native','culture fit','male','female','married','single','native speaker','recent graduate','under 30','under 35','over 50'];const vague=['good communication','great attitude','rockstar','ninja','perfect candidate','strong personality'];return[{review:proxy.some(x=>text.includes(x)),title:'Protected-attribute / proxy language',detail:'Review any age, gender, family-status or proxy wording and keep requirements job-relevant.'},{review:vague.some(x=>text.includes(x)),title:'Subjective requirements',detail:'Replace vague phrases with observable evidence or measurable outcomes.'},{review:!(analysis?.mustHave?.length),title:'Explicit must-haves',detail:'Define non-negotiable, job-relevant criteria before sourcing.'},{review:!(analysis?.competencies?.length||analysis?.interviewFocus?.length),title:'Interview evidence areas',detail:'Define competencies or interview focus areas for consistent assessment.'}]},[prompt,jd,analysis]);
 async function connect(){setLoading(true);setError('');try{const model=provider==='gemini'?'gemini-3.6-flash':provider==='openai'?'gpt-4.1-mini':undefined;await api('ai/connect',{provider,apiKey,model});setConnected(true);setApiKey('');setShowKey(false)}catch(e){fail(e)}finally{setLoading(false)}}
 async function create(){setLoading(true);setError('');try{const d=await api('jd/analyze',{text:prompt});setAnalysis(d);setTitle(d.title||'New role');setJd(d.description||'');setJobId(d.jobId||d.job?.id||'');setStage('job')}catch(e){fail(e)}finally{setLoading(false)}}
 async function requestApproval(action:string){setLoading(true);setError('');try{const d=await control('approvals',{jobId,action,requestedBy:'recruiter',note:`Human review requested for ${ACTION_LABEL[action]||action}.`});setApproval(d);await refreshApprovals()}catch(e){fail(e)}finally{setLoading(false)}}
 async function approve(a:any,after?:()=>void){setLoading(true);setError('');try{const d=await control(`approvals/${a.id}/decision`,{status:'approved',actor:'recruiter',note:'Reviewed and approved by recruiter.'});setApproval(d);await refreshApprovals();if(after)after()}catch(e){fail(e)}finally{setLoading(false)}}
 async function source(){setLoading(true);setError('');try{const d=await api('source/search',{jobId,role:{jobId,title,description:jd,...analysis},limit:8});setCandidates(d.savedCandidates?.length?d.savedCandidates:d.candidates||[]);setStage('source')}catch(e){fail(e)}finally{setLoading(false)}}
 async function score(){setLoading(true);setError('');try{const out:C[]=[];for(const c of candidates){const d=await api('candidate/score',{jobId,candidateId:c.id,candidate:c,requirement:{title,description:jd,...analysis}});out.push({...c,score:d})}setCandidates(out.sort((a,b)=>(b.score?.overall||0)-(a.score?.overall||0)));setStage('screen')}catch(e){fail(e)}finally{setLoading(false)}}
 async function interview(c:C){setSelected(c);setAnswers([]);setLoading(true);setError('');try{const d=await api('interview/plan',{jobId,candidateId:c.id,role:title,competencies:analysis?.competencies||analysis?.interviewFocus||[]});const p=d.plan||{};setInterviewId(d.interview?.id||'');setQuestions((p.questions||[]).map((q:any,i:number)=>typeof q==='string'?{id:String(i+1),question:q}:q).slice(0,5));setStage('interview')}catch(e){fail(e)}finally{setLoading(false)}}
 async function answer(text:string,i:number){const next=[...answers];next[i]=text;setAnswers(next);if(interviewId&&text)try{await api(`interviews/${interviewId}/answers`,{questionId:questions[i]?.id||String(i+1),answer:text})}catch(e){fail(e)}}
 function listen(i:number){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setError('Audio input is not supported in this browser.');return}const r=new SR();r.lang='en-IN';r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=(e:any)=>answer(e.results[0][0].transcript,i);r.start()}
 async function completeInterview(){setLoading(true);setError('');try{const evidence={overall:Math.min(100,70+answers.filter(Boolean).length*6),strengths:['Structured competency responses captured','Role-specific evidence recorded'],concerns:[],answers};if(interviewId)await api(`interviews/${interviewId}/complete`,{evidence});const d=await api('decision',{jobId,candidateId:selected?.id,resume:{overall:selected?.score?.overall||0,strengths:selected?.score?.strengths||[],concerns:selected?.score?.concerns||[]},interview:evidence});setDecision(d);setApproval(d.approval);setStage('decision');await refreshApprovals()}catch(e){fail(e)}finally{setLoading(false)}}
 async function recommendComp(){setLoading(true);setError('');try{const d=await api('compensation/recommend',{jobId,candidateId:selected?.id,observations:[analysis?.compensationMin,analysis?.compensationMax].filter(x=>typeof x==='number').map(x=>({cashMedian:x,currency:'INR'})),internalComparable:analysis?.compensationMin});setComp(d);setApproval(d.approval);setStage('comp');await refreshApprovals()}catch(e){fail(e)}finally{setLoading(false)}}
 async function draftOffer(){setLoading(true);setError('');try{const d=await api('offer/draft',{jobId,candidateId:selected?.id,candidateName:selected?.name,role:title,company:'Smart Scout Demo Company',base:Number(comp?.recommendedBase||comp?.base||analysis?.compensationMin||0),currency:'INR',bonus:comp?.recommendedBonus||comp?.bonus,approvalId:String(approval?.id||'')});setOffer(d);setApproval(d.approval);setStage('offer');await refreshApprovals()}catch(e){fail(e)}finally{setLoading(false)}}
 async function transition(status:string){setLoading(true);setError('');try{const d=await api('offer/transition',{jobId,candidateId:selected?.id,status});setOffer(d);if(status==='accepted')setStage('engagement');}catch(e){fail(e)}finally{setLoading(false)}}
 async function planEngagement(){setLoading(true);try{const d=await api('engagement/plan',{jobId,candidateId:selected?.id,candidateName:selected?.name});setEngagement(d.payload||[]);setStage('engagement')}catch(e){fail(e)}finally{setLoading(false)}}
 async function planOnboarding(){setLoading(true);try{const d=await api('onboarding/plan',{jobId,candidateId:selected?.id,candidateName:selected?.name,role:title,department:analysis?.department,location:analysis?.location,manager:'Hiring Manager',startDate:'30 days after acceptance'});setOnboarding(d.payload||d);setStage('onboarding')}catch(e){fail(e)}finally{setLoading(false)}}
 const currentGate=approvals.find(x=>x.status==='pending')||approval; const canApprove=Boolean(currentGate?.status==='pending');
 return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-slate-200 bg-white px-5 sm:px-8"><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Home</button><span className="mx-4 h-5 w-px bg-slate-200"/><b>Smart Scout</b><span className="ml-4 text-sm font-bold text-slate-400">Recruiting OS</span><div className="ml-auto flex items-center gap-2"><span className="hidden text-xs font-bold text-slate-400 sm:inline">{connected?`${provider} connected`:'AI not connected'}</span><button onClick={()=>setShowKey(true)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><KeyRound className="h-4 w-4"/>API key</button></div></header><div className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto px-5 py-4">{STEPS.map((x,i)=><div key={x} className={`flex shrink-0 items-center gap-2 text-xs font-bold ${stage===x?'text-violet-700':'text-slate-400'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full ${stage===x?'bg-violet-600 text-white':'bg-slate-100'}`}>{i+1}</span>{x}{i<STEPS.length-1&&<ChevronRight className="h-4 w-4 text-slate-300"/>}</div>)}</div></div><main className="mx-auto max-w-6xl p-5 sm:p-8">{error&&<div className="mb-5 flex gap-3 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><span className="flex-1">{error}</span><button onClick={()=>setError('')}><X className="h-4 w-4"/></button></div>}
 {stage==='intent'&&<Card title="Start with hiring intent" sub="One context carries from the hiring need all the way to onboarding."><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={7} placeholder="I need a VP HR for a 1,500-person technology company in Gurgaon. Build the people function and lead HR transformation." className="w-full resize-none rounded-2xl bg-slate-50 p-5 outline-none focus:ring-2 focus:ring-violet-500"/><Action onClick={create} disabled={!prompt.trim()||loading} text="Create JD + save job"/></Card>}
 {stage==='job'&&<Card title={title} sub={`Saved job · ${jobId.slice(0,12)}`}><div className="grid gap-5 lg:grid-cols-2"><Box label="Generated JD"><p className="text-sm leading-7">{jd}</p><div className="mt-4 flex flex-wrap gap-2">{(analysis?.mustHave||[]).map(x=><span key={x} className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">✓ {x}</span>)}</div></Box><Box label="Success profile"><div className="space-y-2">{(analysis?.competencies||analysis?.interviewFocus||[]).map(x=><div key={x} className="flex gap-2 text-sm"><Check className="h-4 w-4 text-violet-600"/>{x}</div>)}</div></Box></div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-2 font-black"><ShieldCheck className="h-5 w-5 text-violet-600"/>Fairness & quality review</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{quality.map((q,i)=><div key={i} className={`rounded-xl border p-3 ${q.review?'border-amber-200 bg-white':'border-emerald-200 bg-emerald-50'}`}><div className="text-xs font-black">{q.review?'REVIEW':'PASS'} · {q.title}</div><div className="mt-1 text-[11px] leading-5 text-slate-600">{q.detail}</div></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><Action onClick={()=>requestApproval('jd_approval')} disabled={loading||approval?.status==='pending'||approval?.status==='approved'} text={approval?.status==='approved'?'JD approved':'Request human JD approval'}/>{approval?.status==='pending'&&<ApproveButton a={approval} onApprove={()=>approve(approval,source)} loading={loading}/>}</div></div></Card>}
 {stage==='source'&&<Card title="Source evidence-backed candidates" sub="Every profile must have a real public URL, source attribution and concrete evidence."><div className="flex justify-end"><Action onClick={score} disabled={!candidates.length||loading} text="Score candidates"/></div><div className="mt-5 grid gap-3 md:grid-cols-2">{candidates.map(c=><Candidate key={c.id||c.profileUrl} c={c}/>)}</div></Card>}
 {stage==='screen'&&<Card title="Candidate intelligence" sub="Select a candidate to run the structured interview."><div className="grid gap-3 md:grid-cols-2">{candidates.map(c=><div key={c.id||c.profileUrl} className="rounded-2xl border border-slate-200 bg-white p-4"><Candidate c={c}/><Action onClick={()=>interview(c)} disabled={loading} text="Interview candidate"/></div>)}</div></Card>}
 {stage==='interview'&&<Card title={`Structured interview · ${selected?.name||'Candidate'}`} sub="Capture evidence against the role competencies. Audio input is optional."><div className="space-y-4">{questions.map((q,i)=><div key={q.id||i} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="text-sm font-black">Q{i+1}. {q.question}</div><textarea value={answers[i]||''} onChange={e=>answer(e.target.value,i)} rows={3} className="mt-3 w-full rounded-xl bg-slate-50 p-3 text-sm outline-none" placeholder="Candidate evidence…"/><button onClick={()=>listen(i)} className="mt-2 inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold"><Mic className="h-4 w-4"/>{listening?'Listening…':'Answer by voice'}</button></div>)}</div><Action onClick={completeInterview} disabled={loading||!questions.length||!answers.some(Boolean)} text="Complete interview + build decision"/></Card>}
 {stage==='decision'&&<Card title="Hiring decision" sub="AI recommendation is never the final decision. Human approval is required before compensation."><Box label="Recommendation"><div className="text-4xl font-black">{decision?.score??'—'}%</div><div className="mt-1 text-sm font-black uppercase">{String(decision?.recommendation||'').replace('_',' ')}</div><div className="mt-4 space-y-2">{(decision?.reasons||[]).map((x:string,i:number)=><div key={i} className="text-sm text-slate-600">• {x}</div>)}</div></Box>{gate(approval,'decision',()=>approve(approval,recommendComp),loading)}</Card>}
 {stage==='comp'&&<Card title="Compensation recommendation" sub="Review market/comparable signals and approve the package before an offer is drafted."><Box label="Recommendation"><div className="text-3xl font-black">₹{Number(comp?.recommendedBase||comp?.base||0).toLocaleString('en-IN')}</div><pre className="mt-3 whitespace-pre-wrap text-xs text-slate-500">{JSON.stringify(comp,null,2)}</pre></Box>{gate(approval,'compensation',()=>approve(approval,draftOffer),loading)}</Card>}
 {stage==='offer'&&<Card title="Offer package" sub="The offer remains blocked until a human approves it."><Box label="Offer"><div className="text-sm font-black">{selected?.name} · {title}</div><div className="mt-3 text-2xl font-black">₹{Number(offer?.base||offer?.state?.payload?.base||0).toLocaleString('en-IN')}</div><div className="mt-2 text-xs font-bold text-amber-700">Status: {offer?.status||offer?.state?.payload?.status||'pending_approval'}</div></Box>{gate(approval,'offer',()=>approve(approval,()=>transition('approved')),loading)}{(offer?.status==='approved'||offer?.state?.payload?.status==='approved')&&<div className="mt-3 flex gap-2"><Action onClick={()=>transition('sent')} disabled={loading} text="Send offer"/><Action onClick={()=>transition('accepted')} disabled={loading} text="Demo: candidate accepts"/></div>}{(offer?.status==='sent'||offer?.state?.payload?.status==='sent')&&<Action onClick={()=>transition('accepted')} disabled={loading} text="Record candidate acceptance"/>}</Card>}
 {stage==='engagement'&&<Card title="Preboarding engagement" sub="Plan is generated only after offer acceptance."><div className="space-y-2">{engagement.map((x:any)=><div key={x.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-sm font-black">{x.subject}</div><div className="text-xs text-slate-500">{x.timing} · {x.channel}</div></div>)}</div><Action onClick={planEngagement} disabled={loading} text={engagement.length?'Refresh engagement plan':'Build engagement plan'}/>{engagement.length>0&&<Action onClick={planOnboarding} disabled={loading} text="Continue to onboarding"/>}</Card>}
 {stage==='onboarding'&&<Card title="Onboarding plan" sub="The final plan is ready for execution through the customer's HRIS/IT systems."><pre className="overflow-auto rounded-2xl bg-slate-950 p-5 text-xs text-slate-200">{JSON.stringify(onboarding,null,2)}</pre><div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800"><Check className="mr-2 inline h-4 w-4"/>Hiring lifecycle plan complete. Execution connectors can now be attached.</div></Card>}
 </main>{showKey&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><div className="text-lg font-black">Connect your AI provider</div><select value={provider} onChange={e=>setProvider(e.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm"><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select><input value={apiKey} onChange={e=>setApiKey(e.target.value)} type="password" placeholder="API key" className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setShowKey(false)} className="rounded-xl px-4 py-2 text-sm font-bold">Cancel</button><button onClick={connect} disabled={!apiKey||loading} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">{loading?'Connecting…':'Connect securely'}</button></div></div></div>}</div>;
 function gate(a:any,action:string,approveNext:()=>void,busy:boolean){if(a?.status==='approved')return <div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800"><Check className="mr-2 inline h-4 w-4"/>Human {action} approval recorded.<div className="mt-3"><Action onClick={approveNext} disabled={busy} text={`Continue to ${action==='decision'?'compensation':action==='compensation'?'offer':'send offer'}`}/></div></div>;return <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="text-sm font-black">Human approval required</div><div className="mt-2 flex flex-wrap gap-2"><Action onClick={()=>requestApproval(action)} disabled={busy||a?.status==='pending'} text={a?.status==='pending'?'Approval requested':'Request approval'}/>{a?.status==='pending'&&<ApproveButton a={a} onApprove={()=>approve(a,approveNext)} loading={busy}/>}</div></div>}
}
function Candidate({c}:{c:C}){return <div className="mb-3 rounded-xl border border-slate-100 bg-white p-3"><div className="flex gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-950 text-[10px] font-black text-white">{c.name.split(' ').map(x=>x[0]).join('')}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><div><div className="text-sm font-black">{c.name}</div><div className="text-[10px] text-slate-400">{c.headline||c.location||''}</div></div>{c.score?.overall&&<span className="rounded-md bg-emerald-50 px-2 py-1 text-xs font-black text-emerald-700">{c.score.overall}%</span>}</div>{c.profileUrl&&<a className="mt-2 block truncate text-[10px] font-bold text-violet-600" href={c.profileUrl} target="_blank" rel="noreferrer">{c.profileUrl}</a>}<div className="mt-2 text-[10px] leading-4 text-slate-500">{c.summary||c.reason||''}</div>{c.evidence?.length&&<div className="mt-2 text-[10px] text-slate-500">Evidence: {c.evidence.join(' · ')}</div>}</div></div></div>}
function Card({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-5"><h1 className="text-2xl font-black tracking-tight">{title}</h1><p className="mt-1 text-sm text-slate-500">{sub}</p></div>{children}</section>}
function Box({label,children}:{label:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">{label}</div><div className="mt-3">{children}</div></div>}
function Action({onClick,disabled,text}:{onClick:()=>void;disabled?:boolean;text:string}){return <button onClick={onClick} disabled={disabled} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-xs font-black text-white disabled:opacity-40"><Sparkles className="h-3.5 w-3.5"/>{text}<ChevronRight className="h-3.5 w-3.5"/></button>}
function ApproveButton({a,onApprove,loading}:{a:any;onApprove:()=>void;loading:boolean}){return <button onClick={onApprove} disabled={loading} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-xs font-black text-white disabled:opacity-40"><Check className="h-3.5 w-3.5"/>{loading?'Approving…':'Approve'}</button>}
