import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Check,ChevronRight,KeyRound,Mic,Sparkles,ShieldCheck,X}from'lucide-react';

type A={title?:string;description?:string;mustHave?:string[];niceToHave?:string[];location?:string;experienceMin?:number;experienceMax?:number;compensationMin?:number;compensationMax?:number;department?:string;competencies?:string[];interviewFocus?:string[]};
type C={id?:string;name:string;headline?:string;location?:string;profileUrl?:string;summary?:string;reason?:string;evidence?:string[];score?:any};
const H={'content-type':'application/json','x-tenant-id':'demo-tenant'};
const STEPS=[['intent','Command'],['job','JD'],['source','Source'],['screen','Shortlist'],['interview','Interview'],['decision','Decision'],['comp','Comp'],['offer','Offer'],['engagement','Engage'],['onboarding','Onboard']];
async function api(p:string,b?:any,m='POST'){const r=await fetch(`/api/recruiting/${p}`,{method:m,headers:H,body:m==='GET'?undefined:JSON.stringify(b||{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
async function cp(p:string,b?:any,m='POST'){const r=await fetch(`/api/control-plane/${p}`,{method:m,headers:H,body:m==='GET'?undefined:JSON.stringify(b||{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Control-plane request failed');return d}

export default function HiringLifecycleV4({onBack}:{onBack?:()=>void}){
 const[stage,setStage]=useState('intent'),[prompt,setPrompt]=useState(''),[jobId,setJobId]=useState(''),[analysis,setAnalysis]=useState<A|null>(null),[title,setTitle]=useState(''),[jd,setJd]=useState(''),[candidates,setCandidates]=useState<C[]>([]),[selected,setSelected]=useState<C|null>(null),[questions,setQuestions]=useState<any[]>([]),[answers,setAnswers]=useState<string[]>([]),[interviewId,setInterviewId]=useState(''),[decision,setDecision]=useState<any>(),[comp,setComp]=useState<any>(),[offer,setOffer]=useState<any>(),[engagement,setEngagement]=useState<any[]>([]),[onboarding,setOnboarding]=useState<any>(),[gate,setGate]=useState<any>(null),[connected,setConnected]=useState(false),[provider,setProvider]=useState('gemini'),[apiKey,setApiKey]=useState(''),[showKey,setShowKey]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[listening,setListening]=useState(false);
 const fail=(e:any)=>setError(e?.message||'Something went wrong');
 useEffect(()=>{api('ai/status',undefined,'GET').then((d:any)=>{setConnected(Boolean(d.connected));setProvider(d.provider||'gemini')}).catch(()=>{})},[]);
 const quality=useMemo(()=>{const t=[prompt,jd,analysis?.description||'',...(analysis?.mustHave||[]),...(analysis?.niceToHave||[])].join(' ').toLowerCase();const proxy=['young','energetic','digital native','culture fit','male','female','married','single','native speaker','recent graduate','under 30','under 35','over 50'];const vague=['good communication','great attitude','rockstar','ninja','perfect candidate','strong personality'];return[{r:proxy.some(x=>t.includes(x)),h:'Protected-attribute / proxy language',d:'Keep requirements tied to job-relevant evidence.'},{r:vague.some(x=>t.includes(x)),h:'Subjective requirements',d:'Replace vague phrases with observable outcomes.'},{r:!(analysis?.mustHave?.length),h:'Explicit must-haves',d:'Define non-negotiable, job-relevant criteria.'},{r:!(analysis?.competencies?.length||analysis?.interviewFocus?.length),h:'Interview evidence areas',d:'Define competencies or interview focus areas.'}]},[prompt,jd,analysis]);
 async function connect(){setLoading(true);try{await api('ai/connect',{provider,apiKey,model:provider==='gemini'?'gemini-3.6-flash':provider==='openai'?'gpt-4.1-mini':undefined});setConnected(true);setApiKey('');setShowKey(false)}catch(e){fail(e)}finally{setLoading(false)}}
 async function create(){setLoading(true);setError('');try{const d=await api('jd/analyze',{text:prompt});setAnalysis(d);setTitle(d.title||'New role');setJd(d.description||'');setJobId(d.jobId||d.job?.id||'');setGate(null);setStage('job')}catch(e){fail(e)}finally{setLoading(false)}}
 async function request(action:string){setLoading(true);setError('');try{setGate(await cp('approvals',{jobId,action,requestedBy:'recruiter',note:`Human review requested for ${action}.`}))}catch(e){fail(e)}finally{setLoading(false)}}
 async function approve(next?:()=>void){if(!gate?.id)return;setLoading(true);try{const d=await cp(`approvals/${gate.id}/decision`,{status:'approved',actor:'recruiter',note:'Reviewed and approved by recruiter.'});setGate(d);next?.()}catch(e){fail(e)}finally{setLoading(false)}}
 async function source(){setLoading(true);setError('');try{const d=await api('source/search',{jobId,role:{jobId,title,description:jd,...analysis},limit:8});setCandidates(d.savedCandidates?.length?d.savedCandidates:d.candidates||[]);setStage('source')}catch(e){fail(e)}finally{setLoading(false)}}
 async function score(){setLoading(true);setError('');try{const out:C[]=[];for(const c of candidates)out.push({...c,score:await api('candidate/score',{jobId,candidateId:c.id,candidate:c,requirement:{title,description:jd,...analysis}})});setCandidates(out.sort((a,b)=>(b.score?.overall||0)-(a.score?.overall||0)));setStage('screen')}catch(e){fail(e)}finally{setLoading(false)}}
 async function interview(c:C){setSelected(c);setAnswers([]);setLoading(true);setError('');try{const d=await api('interview/plan',{jobId,candidateId:c.id,role:title,competencies:analysis?.competencies||analysis?.interviewFocus||[]});setInterviewId(d.interview?.id||'');const p=d.plan||{};setQuestions((p.questions||[]).map((q:any,i:number)=>typeof q==='string'?{id:String(i+1),question:q}:q).slice(0,5));setStage('interview')}catch(e){fail(e)}finally{setLoading(false)}}
 async function answer(text:string,i:number){const a=[...answers];a[i]=text;setAnswers(a);if(interviewId&&text)try{await api(`interviews/${interviewId}/answers`,{questionId:questions[i]?.id||String(i+1),answer:text})}catch(e){fail(e)}}
 function listen(i:number){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setError('Audio input is not supported in this browser.');return}const r=new SR();r.lang='en-IN';r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=(e:any)=>answer(e.results[0][0].transcript,i);r.start()}
 async function complete(){setLoading(true);setError('');try{const evidence={overall:Math.min(100,70+answers.filter(Boolean).length*6),strengths:['Structured competency responses captured','Role-specific evidence recorded'],concerns:[],answers};if(interviewId)await api(`interviews/${interviewId}/complete`,{evidence});const d=await api('decision',{jobId,candidateId:selected?.id,resume:{overall:selected?.score?.overall||0,strengths:selected?.score?.strengths||[],concerns:selected?.score?.concerns||[]},interview:evidence});setDecision(d);setGate(d.approval);setStage('decision')}catch(e){fail(e)}finally{setLoading(false)}}
 async function compensation(){setLoading(true);setError('');try{const d=await api('compensation/recommend',{jobId,candidateId:selected?.id,observations:[analysis?.compensationMin,analysis?.compensationMax].filter(x=>typeof x==='number').map(x=>({cashMedian:x,currency:'INR'})),internalComparable:analysis?.compensationMin});setComp(d);setGate(d.approval);setStage('comp')}catch(e){fail(e)}finally{setLoading(false)}}
 async function draft(){setLoading(true);setError('');try{const d=await api('offer/draft',{jobId,candidateId:selected?.id,candidateName:selected?.name,role:title,company:'Smart Scout Demo Company',base:Number(comp?.recommendedBase||comp?.base||analysis?.compensationMin||0),currency:'INR',bonus:comp?.recommendedBonus||comp?.bonus});setOffer(d);setGate(d.approval);setStage('offer')}catch(e){fail(e)}finally{setLoading(false)}}
 async function transition(status:string){setLoading(true);setError('');try{const d=await api('offer/transition',{jobId,candidateId:selected?.id,status});setOffer(d);if(status==='accepted')setStage('engagement')}catch(e){fail(e)}finally{setLoading(false)}}
 async function planEngagement(){setLoading(true);try{const d=await api('engagement/plan',{jobId,candidateId:selected?.id,candidateName:selected?.name});setEngagement(d.payload||[]);setStage('engagement')}catch(e){fail(e)}finally{setLoading(false)}}
 async function planOnboarding(){setLoading(true);try{const d=await api('onboarding/plan',{jobId,candidateId:selected?.id,candidateName:selected?.name,role:title,department:analysis?.department,location:analysis?.location,manager:'Hiring Manager',startDate:'30 days after acceptance'});setOnboarding(d.payload||d);setStage('onboarding')}catch(e){fail(e)}finally{setLoading(false)}}
 const gateUI=(action:string,next:()=>void)=><div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="font-black">Human approval gate</div><p className="mt-1 text-xs text-slate-600">Smart Scout prepares the evidence; a human owns the decision.</p>{gate?.status==='approved'?<><div className="mt-3 text-sm font-bold text-emerald-700"><Check className="mr-1 inline h-4 w-4"/>Approved</div><Action onClick={next} disabled={loading} text="Continue"/></>:<div className="flex flex-wrap gap-2"><Action onClick={()=>request(action)} disabled={loading||gate?.status==='pending'} text={gate?.status==='pending'?'Approval requested':'Request approval'}/>{gate?.status==='pending'&&<button onClick={()=>approve(next)} disabled={loading} className="mt-4 rounded-xl bg-emerald-600 px-4 py-3 text-xs font-black text-white">Approve</button>}</div>}</div>;
 return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-slate-200 bg-white px-5 sm:px-8"><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Home</button><span className="mx-4 h-5 w-px bg-slate-200"/><b>Smart Scout</b><span className="ml-4 text-sm font-bold text-slate-400">Recruiting OS</span><button onClick={()=>setShowKey(true)} className="ml-auto inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><KeyRound className="h-4 w-4"/>{connected?`${provider} connected`:'Add API key'}</button></header>
 <div className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl gap-1 overflow-x-auto px-4 py-4">{STEPS.map(([id,label],i)=><React.Fragment key={id}><button onClick={()=>i===0&&setStage('intent')} className={`flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-xs font-black ${stage===id?'bg-violet-600 text-white':'text-slate-500 hover:bg-slate-50'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full ${stage===id?'bg-white/20':'bg-slate-100'}`}>{i+1}</span>{label}</button>{i<STEPS.length-1&&<ChevronRight className="mt-3 h-4 w-4 shrink-0 text-slate-300"/>}</React.Fragment>)}</div></div>
 <main className="mx-auto max-w-6xl p-5 sm:p-8">{error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}<button className="float-right" onClick={()=>setError('')}><X className="h-4 w-4"/></button></div>}
 {stage==='intent'&&<Card t="Recruiter command" s="Describe the hire once. Smart Scout turns the intent into a structured hiring workspace."><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={6} placeholder="I need a VP HR for a 1,500-person technology company in Gurgaon. Build the people function, lead HR transformation and partner with the CEO." className="w-full resize-none rounded-2xl border border-slate-200 bg-slate-50 p-5 text-base leading-7 outline-none focus:ring-2 focus:ring-violet-500"/><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric n="Role" v="VP HR"/><Metric n="Context" v="1,500-person tech"/><Metric n="Location" v="Gurgaon"/></div><Action onClick={create} disabled={!prompt.trim()||loading} text="Create role workspace"/></Card>}
 {stage==='job'&&<Card t={title||'Role workspace'} s={`Saved job · ${jobId||'pending'}`}><div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Box l="Generated JD"><p className="text-sm leading-7">{jd}</p><div className="mt-4 flex flex-wrap gap-2">{(analysis?.mustHave||[]).map(x=><span key={x} className="rounded-full bg-emerald-50 px-3 py-1 text-[11px] font-bold text-emerald-700">✓ {x}</span>)}</div></Box><Box l="Role intelligence"><Info k="Department" v={analysis?.department||'People'} /><Info k="Location" v={analysis?.location||'Gurgaon'} /><Info k="Experience" v={`${analysis?.experienceMin??'—'}–${analysis?.experienceMax??'—'} years`} /><Info k="Comp range" v={`₹${Number(analysis?.compensationMin||0).toLocaleString('en-IN')} – ₹${Number(analysis?.compensationMax||0).toLocaleString('en-IN')}`} /></Box></div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="font-black"><ShieldCheck className="mr-2 inline h-5 w-5 text-violet-600"/>Fairness & quality review</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{quality.map((q,i)=><div key={i} className={`rounded-xl border p-3 ${q.r?'border-amber-200 bg-white':'border-emerald-200 bg-emerald-50'}`}><div className="text-xs font-black">{q.r?'REVIEW':'PASS'} · {q.h}</div><div className="mt-1 text-[11px] leading-5 text-slate-600">{q.d}</div></div>)}</div>{gateUI('jd_approval',source)}</div></Card>}
 {stage==='source'&&<Card t="Source candidates" s="Evidence-backed sourcing: profile URL, source attribution and concrete evidence are required."><div className="mb-5 flex items-center justify-between"><div><b>{candidates.length}</b><span className="ml-1 text-sm text-slate-500">profiles found</span></div><Action onClick={score} disabled={!candidates.length||loading} text="Score & shortlist"/></div><div className="grid gap-3 md:grid-cols-2">{candidates.map(c=><div key={c.id||c.profileUrl||c.name}><Candidate c={c}/></div>)}</div></Card>}
 {stage==='screen'&&<Card t="Shortlist intelligence" s="Compare evidence, fit and risks before inviting a candidate to interview."><div className="grid gap-4">{candidates.map((c,i)=><div key={c.id||c.profileUrl||c.name} className={`rounded-2xl border p-5 ${i===0?'border-violet-300 bg-violet-50/40':'border-slate-200 bg-white'}`}><div className="flex items-start gap-4"><div className="flex-1"><Candidate c={c}/></div><div className="hidden w-32 text-right sm:block"><div className="text-3xl font-black text-violet-700">{c.score?.overall||0}%</div><div className="text-[10px] font-black uppercase text-slate-400">overall fit</div></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Mini label="Evidence" value={String(c.evidence?.length||0)}/><Mini label="Strengths" value={String(c.score?.strengths?.length||0)}/><Mini label="Concerns" value={String(c.score?.concerns?.length||0)}/></div><Action onClick={()=>interview(c)} disabled={loading} text="Open interview"/></div>)}</div></Card>}
 {stage==='interview'&&<Card t={`Interview · ${selected?.name||'Candidate'}`} s="Structured questions map to the role competencies. Type or answer by voice."><div className="mb-5 grid gap-3 sm:grid-cols-3"><Metric n="Candidate" v={selected?.name||'—'}/><Metric n="Competencies" v={String((analysis?.competencies||analysis?.interviewFocus||[]).length)}/><Metric n="Evidence captured" v={`${answers.filter(Boolean).length}/${questions.length}`}/></div>{questions.map((q,i)=><div key={q.id||i} className="mb-4 rounded-2xl border border-slate-200 bg-white p-5"><div className="text-[10px] font-black uppercase tracking-widest text-violet-600">Question {i+1}</div><div className="mt-2 text-sm font-black leading-6">{q.question}</div><textarea value={answers[i]||''} onChange={e=>answer(e.target.value,i)} rows={3} className="mt-3 w-full rounded-xl bg-slate-50 p-3 text-sm outline-none focus:ring-2 focus:ring-violet-500" placeholder="Capture observable evidence, not impressions…"/><button onClick={()=>listen(i)} className="mt-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold"><Mic className="mr-1 inline h-4 w-4"/>{listening?'Listening…':'Answer by voice'}</button></div>)}<Action onClick={complete} disabled={loading||!answers.some(Boolean)} text="Complete interview"/></Card>}
 {stage==='decision'&&<Card t="Decision workspace" s="AI recommendation is evidence-based and remains subject to human approval."><div className="grid gap-5 lg:grid-cols-2"><Box l="Recommendation"><div className="text-5xl font-black text-violet-700">{decision?.score??'—'}%</div><div className="mt-2 font-black uppercase">{String(decision?.recommendation||'').replace('_',' ')}</div><div className="mt-4 space-y-2 text-sm text-slate-600">{(decision?.reasons||[]).map((x:string,i:number)=><div key={i}>• {x}</div>)}</div></Box><Box l="Candidate evidence"><div className="font-black">{selected?.name}</div><div className="mt-3 space-y-2 text-xs text-slate-600">{(selected?.evidence||[]).slice(0,5).map(x=><div key={x}>✓ {x}</div>)}</div></Box></div>{gateUI('decision',compensation)}</Card>}
 {stage==='comp'&&<Card t="Compensation workspace" s="Market positioning, internal context and role range inform the package."><div className="grid gap-4 sm:grid-cols-3"><Metric n="Role range" v={`₹${Number(analysis?.compensationMin||0).toLocaleString('en-IN')}–₹${Number(analysis?.compensationMax||0).toLocaleString('en-IN')}`}/><Metric n="Recommended base" v={`₹${Number(comp?.recommendedBase||comp?.base||0).toLocaleString('en-IN')}`}/><Metric n="Currency" v="INR"/></div>{gateUI('compensation',draft)}</Card>}
 {stage==='offer'&&<Card t="Offer workspace" s="The offer is prepared, reviewed and released through explicit human gates."><div className="grid gap-5 lg:grid-cols-2"><Box l="Offer preview"><div className="text-lg font-black">{selected?.name}</div><div className="mt-1 text-sm text-slate-500">{title} · Smart Scout Demo Company</div><div className="mt-5 text-3xl font-black">₹{Number(offer?.base||offer?.state?.payload?.base||comp?.recommendedBase||0).toLocaleString('en-IN')}</div><div className="mt-2 text-xs font-bold text-slate-500">Status: {offer?.status||offer?.state?.payload?.status||'pending approval'}</div></Box><Box l="Release checklist"><Info k="Candidate" v={selected?.name||'—'}/><Info k="Role" v={title}/><Info k="Approval" v={gate?.status||'pending'}/><Info k="Evidence" v="Decision + compensation recorded"/></Box></div>{gateUI('offer',()=>transition('approved'))}{(offer?.status==='approved'||offer?.state?.payload?.status==='approved')&&<div className="flex flex-wrap gap-2"><Action onClick={()=>transition('sent')} disabled={loading} text="Send offer"/><Action onClick={()=>transition('accepted')} disabled={loading} text="Demo: accept"/></div>}{(offer?.status==='sent'||offer?.state?.payload?.status==='sent')&&<Action onClick={()=>transition('accepted')} disabled={loading} text="Record acceptance"/>}</Card>}
 {stage==='engagement'&&<Card t="Preboarding engagement" s="Keep the candidate warm between acceptance and joining."><Action onClick={planEngagement} disabled={loading} text={engagement.length?'Refresh plan':'Build engagement plan'}/><div className="mt-4 space-y-2">{engagement.map(x=><div key={x.id||x.subject} className="rounded-xl border border-slate-200 bg-white p-4"><b className="text-sm">{x.subject}</b><div className="mt-1 text-xs text-slate-500">{x.timing} · {x.channel}</div></div>)}</div>{engagement.length>0&&<Action onClick={planOnboarding} disabled={loading} text="Continue to onboarding"/>}</Card>}
 {stage==='onboarding'&&<Card t="Onboarding workspace" s="The hiring journey is complete and ready for HRIS / IT execution connectors."><div className="rounded-2xl bg-slate-950 p-5 text-xs text-slate-200"><div className="mb-3 font-black text-white">JOINING PACK</div><pre className="overflow-auto">{JSON.stringify(onboarding,null,2)}</pre></div><div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800"><Check className="mr-2 inline h-4 w-4"/>End-to-end hiring plan complete.</div></Card>}
 </main>{showKey&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h2 className="text-lg font-black">Connect AI provider</h2><p className="mt-1 text-xs text-slate-500">Use your own provider key for this workspace.</p><select value={provider} onChange={e=>setProvider(e.target.value)} className="mt-4 w-full rounded-xl border p-3"><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="API key" className="mt-3 w-full rounded-xl border p-3"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setShowKey(false)} className="px-4 py-2 text-sm font-bold">Cancel</button><button onClick={connect} disabled={!apiKey||loading} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white">Connect</button></div></div></div>}</div>
}
function Candidate({c}:{c:C}){return <div className="rounded-xl border border-slate-100 bg-white p-3"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-slate-950 text-[10px] font-black text-white">{c.name.split(' ').map(x=>x[0]).join('')}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><b className="text-sm">{c.name}</b>{c.score?.overall!=null&&<span className="rounded bg-emerald-50 px-2 py-1 text-xs font-black text-emerald-700">{c.score.overall}%</span>}</div><div className="text-[10px] text-slate-400">{c.headline||c.location||''}</div>{c.profileUrl&&<a href={c.profileUrl} target="_blank" rel="noreferrer" className="mt-2 block truncate text-[10px] font-bold text-violet-600">{c.profileUrl}</a>}<div className="mt-2 text-[10px] leading-4 text-slate-500">{c.summary||c.reason||''}</div>{c.evidence?.length?<div className="mt-2 text-[10px] leading-4 text-slate-500"><b>Evidence:</b> {c.evidence.join(' · ')}</div>:null}</div></div></div>}
function Card({t,s,children}:{t:string;s:string;children:React.ReactNode}){return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h1 className="text-2xl font-black tracking-tight">{t}</h1><p className="mt-1 text-sm text-slate-500">{s}</p><div className="mt-5">{children}</div></section>}
function Box({l,children}:{l:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">{l}</div><div className="mt-3">{children}</div></div>}
function Metric({n,v}:{n:string;v:string}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">{n}</div><div className="mt-1 text-sm font-black">{v}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><div className="text-[9px] font-black uppercase text-slate-400">{label}</div><div className="mt-1 text-sm font-black">{value}</div></div>}
function Info({k,v}:{k:string;v:string}){return <div className="flex items-center justify-between border-b border-slate-200 py-2 text-xs"><span className="text-slate-400">{k}</span><b>{v}</b></div>}
function Action({onClick,disabled,text}:{onClick:()=>void;disabled?:boolean;text:string}){return <button onClick={onClick} disabled={disabled} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-xs font-black text-white disabled:opacity-40"><Sparkles className="h-3.5 w-3.5"/>{text}<ChevronRight className="h-3.5 w-3.5"/></button>}
