import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Check,ChevronRight,KeyRound,Mic,Sparkles,ShieldCheck,X}from'lucide-react';

type A={title?:string;description?:string;mustHave?:string[];niceToHave?:string[];location?:string;compensationMin?:number;compensationMax?:number;department?:string;competencies?:string[];interviewFocus?:string[]};
type C={id?:string;name:string;headline?:string;location?:string;profileUrl?:string;summary?:string;reason?:string;evidence?:string[];score?:any;};
const H={'content-type':'application/json','x-tenant-id':'demo-tenant'};const STEPS=['intent','job','source','screen','interview','decision','comp','offer','engagement','onboarding'];
async function api(p:string,b?:any,m='POST'){const r=await fetch(`/api/recruiting/${p}`,{method:m,headers:H,body:m==='GET'?undefined:JSON.stringify(b||{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
async function cp(p:string,b?:any,m='POST'){const r=await fetch(`/api/control-plane/${p}`,{method:m,headers:H,body:m==='GET'?undefined:JSON.stringify(b||{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Control-plane request failed');return d}
export default function HiringLifecycleV4({onBack}:{onBack?:()=>void}){
 const[stage,setStage]=useState('intent'),[prompt,setPrompt]=useState(''),[jobId,setJobId]=useState(''),[analysis,setAnalysis]=useState<A|null>(null),[title,setTitle]=useState(''),[jd,setJd]=useState(''),[candidates,setCandidates]=useState<C[]>([]),[selected,setSelected]=useState<C|null>(null),[questions,setQuestions]=useState<any[]>([]),[answers,setAnswers]=useState<string[]>([]),[interviewId,setInterviewId]=useState(''),[decision,setDecision]=useState<any>(),[comp,setComp]=useState<any>(),[offer,setOffer]=useState<any>(),[engagement,setEngagement]=useState<any[]>([]),[onboarding,setOnboarding]=useState<any>(),[gate,setGate]=useState<any>(null),[connected,setConnected]=useState(false),[provider,setProvider]=useState('gemini'),[apiKey,setApiKey]=useState(''),[showKey,setShowKey]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[listening,setListening]=useState(false);
 const fail=(e:any)=>setError(e?.message||'Something went wrong');
 useEffect(()=>{api('ai/status',undefined,'GET').then((d:any)=>{setConnected(Boolean(d.connected));setProvider(d.provider||'gemini')}).catch(()=>{})},[]);
 const quality=useMemo(()=>{const t=[prompt,jd,analysis?.description||'',...(analysis?.mustHave||[]),...(analysis?.niceToHave||[])].join(' ').toLowerCase();const proxy=['young','energetic','digital native','culture fit','male','female','married','single','native speaker','recent graduate','under 30','under 35','over 50'];const vague=['good communication','great attitude','rockstar','ninja','perfect candidate','strong personality'];return[{r:proxy.some(x=>t.includes(x)),h:'Protected-attribute / proxy language',d:'Keep requirements tied to job-relevant evidence.'},{r:vague.some(x=>t.includes(x)),h:'Subjective requirements',d:'Replace vague phrases with observable outcomes.'},{r:!(analysis?.mustHave?.length),h:'Explicit must-haves',d:'Define non-negotiable, job-relevant criteria.'},{r:!(analysis?.competencies?.length||analysis?.interviewFocus?.length),h:'Interview evidence areas',d:'Define competencies or interview focus areas.'}]},[prompt,jd,analysis]);
 async function connect(){setLoading(true);try{await api('ai/connect',{provider,apiKey,model:provider==='gemini'?'gemini-3.6-flash':provider==='openai'?'gpt-4.1-mini':undefined});setConnected(true);setApiKey('');setShowKey(false)}catch(e){fail(e)}finally{setLoading(false)}}
 async function create(){setLoading(true);try{const d=await api('jd/analyze',{text:prompt});setAnalysis(d);setTitle(d.title||'New role');setJd(d.description||'');setJobId(d.jobId||d.job?.id||'');setGate(null);setStage('job')}catch(e){fail(e)}finally{setLoading(false)}}
 async function request(action:string){setLoading(true);try{const d=await cp('approvals',{jobId,action,requestedBy:'recruiter',note:`Human review requested for ${action}.`});setGate(d)}catch(e){fail(e)}finally{setLoading(false)}}
 async function approve(next?:()=>void){if(!gate?.id)return;setLoading(true);try{const d=await cp(`approvals/${gate.id}/decision`,{status:'approved',actor:'recruiter',note:'Reviewed and approved by recruiter.'});setGate(d);if(next)next()}catch(e){fail(e)}finally{setLoading(false)}}
 async function source(){setLoading(true);try{const d=await api('source/search',{jobId,role:{jobId,title,description:jd,...analysis},limit:8});setCandidates(d.savedCandidates?.length?d.savedCandidates:d.candidates||[]);setStage('source')}catch(e){fail(e)}finally{setLoading(false)}}
 async function score(){setLoading(true);try{const out:C[]=[];for(const c of candidates){out.push({...c,score:await api('candidate/score',{jobId,candidateId:c.id,candidate:c,requirement:{title,description:jd,...analysis}})})}setCandidates(out.sort((a,b)=>(b.score?.overall||0)-(a.score?.overall||0)));setStage('screen')}catch(e){fail(e)}finally{setLoading(false)}}
 async function interview(c:C){setSelected(c);setAnswers([]);setLoading(true);try{const d=await api('interview/plan',{jobId,candidateId:c.id,role:title,competencies:analysis?.competencies||analysis?.interviewFocus||[]});setInterviewId(d.interview?.id||'');const p=d.plan||{};setQuestions((p.questions||[]).map((q:any,i:number)=>typeof q==='string'?{id:String(i+1),question:q}:q).slice(0,5));setStage('interview')}catch(e){fail(e)}finally{setLoading(false)}}
 async function answer(text:string,i:number){const a=[...answers];a[i]=text;setAnswers(a);if(interviewId&&text)try{await api(`interviews/${interviewId}/answers`,{questionId:questions[i]?.id||String(i+1),answer:text})}catch(e){fail(e)}}
 function listen(i:number){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setError('Audio input is not supported in this browser.');return}const r=new SR();r.lang='en-IN';r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=(e:any)=>answer(e.results[0][0].transcript,i);r.start()}
 async function complete(){setLoading(true);try{const evidence={overall:Math.min(100,70+answers.filter(Boolean).length*6),strengths:['Structured competency responses captured','Role-specific evidence recorded'],concerns:[],answers};if(interviewId)await api(`interviews/${interviewId}/complete`,{evidence});const d=await api('decision',{jobId,candidateId:selected?.id,resume:{overall:selected?.score?.overall||0,strengths:selected?.score?.strengths||[],concerns:selected?.score?.concerns||[]},interview:evidence});setDecision(d);setGate(d.approval);setStage('decision')}catch(e){fail(e)}finally{setLoading(false)}}
 async function compensation(){setLoading(true);try{const d=await api('compensation/recommend',{jobId,candidateId:selected?.id,observations:[analysis?.compensationMin,analysis?.compensationMax].filter(x=>typeof x==='number').map(x=>({cashMedian:x,currency:'INR'})),internalComparable:analysis?.compensationMin});setComp(d);setGate(d.approval);setStage('comp')}catch(e){fail(e)}finally{setLoading(false)}}
 async function draft(){setLoading(true);try{const d=await api('offer/draft',{jobId,candidateId:selected?.id,candidateName:selected?.name,role:title,company:'Smart Scout Demo Company',base:Number(comp?.recommendedBase||comp?.base||analysis?.compensationMin||0),currency:'INR',bonus:comp?.recommendedBonus||comp?.bonus});setOffer(d);setGate(d.approval);setStage('offer')}catch(e){fail(e)}finally{setLoading(false)}}
 async function transition(status:string){setLoading(true);try{const d=await api('offer/transition',{jobId,candidateId:selected?.id,status});setOffer(d);if(status==='accepted')setStage('engagement')}catch(e){fail(e)}finally{setLoading(false)}}
 async function planEngagement(){setLoading(true);try{const d=await api('engagement/plan',{jobId,candidateId:selected?.id,candidateName:selected?.name});setEngagement(d.payload||[]);setStage('engagement')}catch(e){fail(e)}finally{setLoading(false)}}
 async function planOnboarding(){setLoading(true);try{const d=await api('onboarding/plan',{jobId,candidateId:selected?.id,candidateName:selected?.name,role:title,department:analysis?.department,location:analysis?.location,manager:'Hiring Manager',startDate:'30 days after acceptance'});setOnboarding(d.payload||d);setStage('onboarding')}catch(e){fail(e)}finally{setLoading(false)}}
 const gateUI=(action:string,next:()=>void)=><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="font-black">Human approval required</div>{gate?.status==='approved'?<><div className="mt-2 text-sm font-bold text-emerald-700"><Check className="mr-1 inline h-4 w-4"/>Approved</div><Action onClick={next} disabled={loading} text="Continue"/></>:<div className="flex flex-wrap gap-2"><Action onClick={()=>request(action)} disabled={loading||gate?.status==='pending'} text={gate?.status==='pending'?'Approval requested':'Request approval'}/>{gate?.status==='pending'&&<button onClick={()=>approve(next)} disabled={loading} className="mt-5 rounded-xl bg-emerald-600 px-4 py-3 text-xs font-black text-white">Approve</button>}</div>}</div>;
 return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-slate-200 bg-white px-5 sm:px-8"><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Home</button><span className="mx-4 h-5 w-px bg-slate-200"/><b>Smart Scout</b><span className="ml-4 text-sm font-bold text-slate-400">Recruiting OS</span><button onClick={()=>setShowKey(true)} className="ml-auto inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><KeyRound className="h-4 w-4"/>{connected?`${provider} connected`:'Add API key'}</button></header><div className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto px-5 py-4">{STEPS.map((x,i)=><div key={x} className={`flex shrink-0 items-center gap-2 text-xs font-bold ${stage===x?'text-violet-700':'text-slate-400'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full ${stage===x?'bg-violet-600 text-white':'bg-slate-100'}`}>{i+1}</span>{x}{i<9&&<ChevronRight className="h-4 w-4 text-slate-300"/>}</div>)}</div></div><main className="mx-auto max-w-6xl p-5 sm:p-8">{error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}<button className="float-right" onClick={()=>setError('')}><X className="h-4 w-4"/></button></div>}
 {stage==='intent'&&<Card t="Start with hiring intent" s="One context carries through the complete hire."><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={7} placeholder="I need a VP HR for a 1,500-person technology company in Gurgaon. Build the people function and lead HR transformation." className="w-full rounded-2xl bg-slate-50 p-5 outline-none"/><Action onClick={create} disabled={!prompt.trim()||loading} text="Create JD + save job"/></Card>}
 {stage==='job'&&<Card t={title} s={`Saved job · ${jobId.slice(0,12)}`}><div className="grid gap-5 lg:grid-cols-2"><Box l="Generated JD"><p className="text-sm leading-7">{jd}</p></Box><Box l="Success profile">{(analysis?.competencies||analysis?.interviewFocus||[]).map(x=><div key={x} className="mb-2 text-sm"><Check className="mr-2 inline h-4 w-4 text-violet-600"/>{x}</div>)}</Box></div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="font-black"><ShieldCheck className="mr-2 inline h-5 w-5"/>Fairness & quality review</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{quality.map((q,i)=><div key={i} className={`rounded-xl border p-3 ${q.r?'border-amber-200 bg-white':'border-emerald-200 bg-emerald-50'}`}><div className="text-xs font-black">{q.r?'REVIEW':'PASS'} · {q.h}</div><div className="mt-1 text-[11px] text-slate-600">{q.d}</div></div>)}</div>{gateUI('jd_approval',source)}</div></Card>}
 {stage==='source'&&<Card t="Evidence-backed sourcing" s="Real public URL + source + concrete evidence are mandatory."><Action onClick={score} disabled={!candidates.length||loading} text="Score candidates"/><div className="mt-5 grid gap-3 md:grid-cols-2">{candidates.map(c=><Candidate key={c.id||c.profileUrl} c={c}/>)}</div></Card>}
 {stage==='screen'&&<Card t="Candidate intelligence" s="Select the strongest evidence-backed candidate for a structured interview."><div className="grid gap-3 md:grid-cols-2">{candidates.map(c=><div key={c.id||c.profileUrl} className="rounded-2xl border border-slate-200 bg-white p-4"><Candidate c={c}/><Action onClick={()=>interview(c)} disabled={loading} text="Run interview"/></div>)}</div></Card>}
 {stage==='interview'&&<Card t={`Structured interview · ${selected?.name||''}`} s="Evidence is persisted. Voice input is optional.">{questions.map((q,i)=><div key={q.id||i} className="mb-4 rounded-2xl border border-slate-200 p-4"><div className="text-sm font-black">Q{i+1}. {q.question}</div><textarea value={answers[i]||''} onChange={e=>answer(e.target.value,i)} rows={3} className="mt-3 w-full rounded-xl bg-slate-50 p-3 text-sm"/><button onClick={()=>listen(i)} className="mt-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold"><Mic className="mr-1 inline h-4 w-4"/>{listening?'Listening…':'Answer by voice'}</button></div>)}<Action onClick={complete} disabled={loading||!answers.some(Boolean)} text="Complete interview + decision"/></Card>}
 {stage==='decision'&&<Card t="Hiring decision" s="AI recommends; a human approves the decision before compensation."><Box l="Recommendation"><div className="text-4xl font-black">{decision?.score??'—'}%</div><div className="mt-1 font-black uppercase">{String(decision?.recommendation||'').replace('_',' ')}</div><div className="mt-4 space-y-2 text-sm text-slate-600">{(decision?.reasons||[]).map((x:string,i:number)=><div key={i}>• {x}</div>)}</div></Box>{gateUI('decision',compensation)}</Card>}
 {stage==='comp'&&<Card t="Compensation recommendation" s="Approve the package before an offer is drafted."><Box l="Recommendation"><div className="text-3xl font-black">₹{Number(comp?.recommendedBase||comp?.base||0).toLocaleString('en-IN')}</div></Box>{gateUI('compensation',draft)}</Card>}
 {stage==='offer'&&<Card t="Offer package" s="The offer cannot be sent without human approval."><Box l="Offer"><div className="font-black">{selected?.name} · {title}</div><div className="mt-2 text-2xl font-black">₹{Number(offer?.base||offer?.state?.payload?.base||0).toLocaleString('en-IN')}</div><div className="mt-1 text-xs font-bold">Status: {offer?.status||offer?.state?.payload?.status||'pending_approval'}</div></Box>{gateUI('offer',()=>transition('approved'))}{(offer?.status==='approved'||offer?.state?.payload?.status==='approved')&&<div className="flex flex-wrap gap-2"><Action onClick={()=>transition('sent')} disabled={loading} text="Send offer"/><Action onClick={()=>transition('accepted')} disabled={loading} text="Demo: candidate accepts"/></div>}{(offer?.status==='sent'||offer?.state?.payload?.status==='sent')&&<Action onClick={()=>transition('accepted')} disabled={loading} text="Record acceptance"/>}</Card>}
 {stage==='engagement'&&<Card t="Preboarding engagement" s="Generated only after offer acceptance."><Action onClick={planEngagement} disabled={loading} text={engagement.length?'Refresh plan':'Build engagement plan'}/>{engagement.map(x=><div key={x.id} className="mt-2 rounded-xl border border-slate-200 p-4 text-sm"><b>{x.subject}</b><div className="text-xs text-slate-500">{x.timing} · {x.channel}</div></div>)}{engagement.length>0&&<Action onClick={planOnboarding} disabled={loading} text="Continue to onboarding"/>}</Card>}
 {stage==='onboarding'&&<Card t="Onboarding plan" s="Ready for HRIS/IT execution connectors."><pre className="overflow-auto rounded-2xl bg-slate-950 p-5 text-xs text-slate-200">{JSON.stringify(onboarding,null,2)}</pre><div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800"><Check className="mr-2 inline h-4 w-4"/>End-to-end hiring plan complete.</div></Card>}
 </main>{showKey&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h2 className="text-lg font-black">Connect AI provider</h2><select value={provider} onChange={e=>setProvider(e.target.value)} className="mt-4 w-full rounded-xl border p-3"><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="API key" className="mt-3 w-full rounded-xl border p-3"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setShowKey(false)} className="px-4 py-2 text-sm font-bold">Cancel</button><button onClick={connect} disabled={!apiKey||loading} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white">Connect</button></div></div></div>}</div>
}
function Candidate({c}:{c:C}){return <div className="rounded-xl border border-slate-100 bg-white p-3"><div className="flex gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-950 text-[10px] font-black text-white">{c.name.split(' ').map(x=>x[0]).join('')}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b className="text-sm">{c.name}</b>{c.score?.overall&&<span className="rounded bg-emerald-50 px-2 py-1 text-xs font-black text-emerald-700">{c.score.overall}%</span>}</div><div className="text-[10px] text-slate-400">{c.headline||c.location||''}</div>{c.profileUrl&&<a href={c.profileUrl} target="_blank" rel="noreferrer" className="mt-2 block truncate text-[10px] font-bold text-violet-600">{c.profileUrl}</a>}<div className="mt-2 text-[10px] leading-4 text-slate-500">{c.summary||c.reason||''}</div>{c.evidence?.length&&<div className="mt-2 text-[10px] text-slate-500">Evidence: {c.evidence.join(' · ')}</div>}</div></div></div>}
function Card({t,s,children}:{t:string;s:string;children:React.ReactNode}){return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h1 className="text-2xl font-black tracking-tight">{t}</h1><p className="mt-1 text-sm text-slate-500">{s}</p><div className="mt-5">{children}</div></section>}
function Box({l,children}:{l:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">{l}</div><div className="mt-3">{children}</div></div>}
function Action({onClick,disabled,text}:{onClick:()=>void;disabled?:boolean;text:string}){return <button onClick={onClick} disabled={disabled} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-xs font-black text-white disabled:opacity-40"><Sparkles className="h-3.5 w-3.5"/>{text}<ChevronRight className="h-3.5 w-3.5"/></button>}
