import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Check,ChevronRight,KeyRound,Loader2,ShieldCheck,X}from'lucide-react';
import BrowserSourceConnect from'./BrowserSourceConnect';

type Stage='intent'|'job'|'source'|'screen'|'interview'|'decision'|'comp'|'offer'|'engagement'|'onboarding';
type Candidate={id?:string;name:string;role?:string;headline?:string;location?:string;profileUrl?:string;source?:string;summary?:string;reason?:string;evidence?:string[];score?:any};
type Analysis={title?:string;description?:string;mustHave?:string[];niceToHave?:string[];location?:string;experienceMin?:number;experienceMax?:number;compensationMin?:number;compensationMax?:number;department?:string;competencies?:string[];interviewFocus?:string[]};
const stages:Array<[Stage,string]>= [['intent','Command'],['job','JD'],['source','Source'],['screen','Shortlist'],['interview','Interview'],['decision','Decision'],['comp','Comp'],['offer','Offer'],['engagement','Engage'],['onboarding','Onboard']];
const api=async(path:string,body?:any,method='POST')=>{const r=await fetch(`/api/recruiting/${path}`,{method,headers:{'content-type':'application/json'},credentials:'include',body:method==='GET'?undefined:JSON.stringify(body||{})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d};
const cp=async(path:string,body?:any,method='POST')=>{const r=await fetch(`/api/control-plane/${path}`,{method,headers:{'content-type':'application/json'},credentials:'include',body:method==='GET'?undefined:JSON.stringify(body||{})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Approval request failed');return d};

export default function HiringLifecycleRelease({onBack}:{onBack?:()=>void}){
 const[stage,setStage]=useState<Stage>('intent'),[prompt,setPrompt]=useState(''),[jobId,setJobId]=useState(''),[title,setTitle]=useState(''),[jd,setJd]=useState(''),[analysis,setAnalysis]=useState<Analysis|null>(null),[candidates,setCandidates]=useState<Candidate[]>([]),[selected,setSelected]=useState<Candidate|null>(null),[questions,setQuestions]=useState<any[]>([]),[answers,setAnswers]=useState<string[]>([]),[interviewId,setInterviewId]=useState(''),[decision,setDecision]=useState<any>(null),[comp,setComp]=useState<any>(null),[offer,setOffer]=useState<any>(null),[engagement,setEngagement]=useState<any[]>([]),[onboarding,setOnboarding]=useState<any>(null),[approvals,setApprovals]=useState<any[]>([]),[sourceOpen,setSourceOpen]=useState(false),[source,setSource]=useState<'linkedin'|'naukri'>('linkedin'),[sourceQuery,setSourceQuery]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[aiConnected,setAiConnected]=useState(false),[provider,setProvider]=useState('gemini'),[apiKey,setApiKey]=useState(''),[showKey,setShowKey]=useState(false);
 const currentIndex=stages.findIndex(x=>x[0]===stage);
 const jdApproval=useMemo(()=>approvals.find(x=>x.action==='jd_approval'),[approvals]);
 const decisionApproval=useMemo(()=>approvals.find(x=>x.action==='decision'),[approvals]);
 const compApproval=useMemo(()=>approvals.find(x=>x.action==='compensation'),[approvals]);
 const offerApproval=useMemo(()=>approvals.find(x=>x.action==='offer'),[approvals]);
 const quality=useMemo(()=>{const text=[prompt,jd,analysis?.description||'',...(analysis?.mustHave||[]),...(analysis?.niceToHave||[])].join(' ').toLowerCase();const proxy=['young','energetic','digital native','culture fit','male','female','married','single','native speaker','recent graduate','under 30','under 35','over 50'];const vague=['good communication','great attitude','rockstar','ninja','perfect candidate','strong personality'];return[{hit:proxy.some(x=>text.includes(x)),label:'Protected-attribute / proxy language',detail:'Keep requirements tied to job-relevant evidence.'},{hit:vague.some(x=>text.includes(x)),label:'Subjective requirements',detail:'Replace vague phrases with observable outcomes.'},{hit:!(analysis?.mustHave?.length),label:'Explicit must-haves',detail:'Define non-negotiable job-relevant criteria.'},{hit:!(analysis?.competencies?.length||analysis?.interviewFocus?.length),label:'Interview evidence areas',detail:'Define competencies or interview focus areas.'}]},[prompt,jd,analysis]);
 const refreshApprovals=async()=>{if(!jobId)return;try{const d=await cp(`approvals?jobId=${encodeURIComponent(jobId)}`,undefined,'GET');setApprovals(d.approvals||[])}catch{}};
 useEffect(()=>{api('ai/status',undefined,'GET').then(d=>{setAiConnected(Boolean(d.connected));setProvider(d.provider||'gemini')}).catch(()=>{});},[]);
 useEffect(()=>{if(jobId)refreshApprovals()},[jobId]);
 async function connectAI(){setLoading(true);setError('');try{const d=await api('ai/connect',{provider,apiKey,model:provider==='gemini'?'gemini-3.6-flash':provider==='openai'?'gpt-4.1-mini':undefined});setAiConnected(true);setProvider(d.provider||provider);setApiKey('');setShowKey(false)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function createJob(){setLoading(true);setError('');try{const d=await api('jd/analyze',{text:prompt});setJobId(d.jobId||d.job?.id||'');setTitle(d.title||'New role');setJd(d.description||'');setAnalysis(d);setApprovals([]);setStage('job')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function requestApproval(action:string){if(!jobId)return;setLoading(true);setError('');try{await cp('approvals',{jobId,action,requestedBy:'recruiter',note:`Human review requested for ${action}.`});await refreshApprovals()}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function approve(id:string){setLoading(true);setError('');try{await cp(`approvals/${id}/decision`,{status:'approved',note:'Reviewed and approved by recruiter.'});await refreshApprovals()}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 function openSource(){if(jdApproval?.status!=='approved'){setError('Approve the JD before sourcing candidates.');return}setSourceQuery(`${title} ${analysis?.location||''} ${analysis?.department||''}`.trim());setSourceOpen(true)}
 async function runSource(){setLoading(true);setError('');try{const d=await api('browser-source/search',{jobId,source,query:sourceQuery,limit:8});setCandidates(d.savedCandidates||d.candidates||[]);setSourceOpen(false);setStage('source')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function scoreCandidates(){setLoading(true);setError('');try{const scored=[] as Candidate[];for(const c of candidates){const score=await api('candidate/score',{jobId,candidateId:c.id,candidate:c,requirement:{title,description:jd,...analysis}});scored.push({...c,score})}setCandidates(scored.sort((a,b)=>(b.score?.overall||0)-(a.score?.overall||0)));setStage('screen')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function planInterview(c:Candidate){setSelected(c);setAnswers([]);setLoading(true);setError('');try{const d=await api('interview/plan',{jobId,candidateId:c.id,role:title,competencies:analysis?.competencies||analysis?.interviewFocus||[]});setInterviewId(d.interview?.id||'');setQuestions((d.plan?.questions||[]).map((q:any,i:number)=>typeof q==='string'?{id:String(i+1),question:q}:q).slice(0,5));setStage('interview')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function saveAnswer(i:number,text:string){const next=[...answers];next[i]=text;setAnswers(next);if(interviewId&&text)try{await api(`interviews/${interviewId}/answers`,{questionId:questions[i]?.id||String(i+1),answer:text})}catch(e:any){setError(e.message)}}
 async function completeInterview(){setLoading(true);setError('');try{const evidence={overall:Math.min(100,70+answers.filter(Boolean).length*6),strengths:['Structured competency responses captured','Role-specific evidence recorded'],concerns:[],answers};if(interviewId)await api(`interviews/${interviewId}/complete`,{evidence});const d=await api('decision',{jobId,candidateId:selected?.id,resume:{overall:selected?.score?.overall||0,strengths:selected?.score?.strengths||[],concerns:selected?.score?.concerns||[]},interview:evidence});setDecision(d);await refreshApprovals();setStage('decision')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function approveDecisionAndContinue(){if(decisionApproval?.status!=='approved'){if(decisionApproval?.id)await approve(decisionApproval.id);else return requestApproval('decision')}setStage('comp')}
 async function recommendComp(){setLoading(true);setError('');try{const d=await api('compensation/recommend',{jobId,candidateId:selected?.id,observations:[analysis?.compensationMin,analysis?.compensationMax].filter(x=>typeof x==='number').map(x=>({cashMedian:x,currency:'INR'})),internalComparable:analysis?.compensationMin});setComp(d);await refreshApprovals();setStage('comp')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function draftOffer(){setLoading(true);setError('');try{const d=await api('offer/draft',{jobId,candidateId:selected?.id,candidateName:selected?.name,role:title,company:'Smart Scout Demo Company',base:Number(comp?.recommendedBase||comp?.base||analysis?.compensationMin||0),currency:'INR',bonus:comp?.recommendedBonus||comp?.bonus});setOffer(d);await refreshApprovals();setStage('offer')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function sendOffer(status:'approved'|'sent'){setLoading(true);setError('');try{const d=await api('offer/transition',{jobId,candidateId:selected?.id,status});setOffer(d);await refreshApprovals();if(status==='sent')setStage('engagement')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function engagementPlan(){setLoading(true);try{const d=await api('engagement/plan',{jobId,candidateId:selected?.id,candidateName:selected?.name});setEngagement(d.payload||[]);setStage('engagement')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function onboardingPlan(){setLoading(true);try{const d=await api('onboarding/plan',{jobId,candidateId:selected?.id,candidateName:selected?.name,role:title,department:analysis?.department,location:analysis?.location,manager:'Hiring Manager',startDate:'30 days after acceptance'});setOnboarding(d.payload||d);setStage('onboarding')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="sticky top-0 z-30 flex min-h-16 items-center gap-3 border-b border-slate-200 bg-white px-4 py-3 sm:px-8"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Home</button><span className="h-5 w-px bg-slate-200"/><b>Smart Scout</b><span className="text-sm font-bold text-slate-400">Recruiting OS</span><button onClick={()=>setShowKey(true)} className="ml-auto inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><KeyRound className="h-4 w-4"/>{aiConnected?`${provider} connected`:'Add AI key'}</button></header>
 <div className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl gap-1 overflow-x-auto px-4 py-3">{stages.map(([id,label],i)=><React.Fragment key={id}><button onClick={()=>i<=currentIndex&&setStage(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-xs font-black ${stage===id?'bg-violet-600 text-white':i<currentIndex?'text-violet-700 hover:bg-violet-50':'text-slate-400'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full ${stage===id?'bg-white/20':i<currentIndex?'bg-violet-100':'bg-slate-100'}`}>{i<currentIndex?<Check className="h-4 w-4"/>:i+1}</span>{label}</button>{i<stages.length-1&&<ChevronRight className="mt-3 h-4 w-4 shrink-0 text-slate-300"/>}</React.Fragment>)}</div></div>
 <main className="mx-auto max-w-6xl p-4 sm:p-8">{error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}<button className="float-right" onClick={()=>setError('')}><X className="h-4 w-4"/></button></div>}
 {stage==='intent'&&<Card title="Recruiter command" sub="Describe the hire once. Smart Scout creates the role workspace and carries the same context through the journey."><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={7} placeholder="I need a VP HR for a 1,500-person technology company in Gurgaon. Build the people function, lead HR transformation and partner with the CEO." className="w-full resize-none rounded-2xl border border-slate-200 bg-slate-50 p-5 text-base leading-7 outline-none focus:ring-2 focus:ring-violet-500"/><div className="mt-4 grid gap-3 sm:grid-cols-3"><Info k="Role" v="VP HR"/><Info k="Context" v="1,500-person technology"/><Info k="Location" v="Gurgaon"/></div><Action onClick={createJob} disabled={!prompt.trim()||loading} text="Create role workspace"/></Card>}
 {stage==='job'&&<Card title={title||'Role workspace'} sub={`Saved job · ${jobId||'pending'}`}><div className="grid gap-5 lg:grid-cols-[1.45fr_.55fr]"><Box label="Generated JD"><p className="text-sm leading-7 text-slate-700">{jd}</p><div className="mt-4 flex flex-wrap gap-2">{(analysis?.mustHave||[]).map(x=><span key={x} className="rounded-full bg-emerald-50 px-3 py-1 text-[11px] font-bold text-emerald-700">✓ {x}</span>)}</div></Box><Box label="Role intelligence"><Info k="Department" v={analysis?.department||'People'}/><Info k="Experience" v={`${analysis?.experienceMin??'—'}–${analysis?.experienceMax??'—'} years`}/><Info k="Location" v={analysis?.location||'Gurgaon'}/><Info k="Comp" v={`₹${Number(analysis?.compensationMin||0).toLocaleString('en-IN')} – ₹${Number(analysis?.compensationMax||0).toLocaleString('en-IN')}`}/></Box></div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-2 font-black"><ShieldCheck className="h-5 w-5 text-violet-600"/>Fairness & quality review</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{quality.map((q,i)=><div key={i} className={`rounded-xl border p-3 ${q.hit?'border-amber-200 bg-white':'border-emerald-200 bg-emerald-50'}`}><div className="text-xs font-black">{q.hit?'REVIEW':'PASS'} · {q.label}</div><div className="mt-1 text-[11px] leading-5 text-slate-600">{q.detail}</div></div>)}</div><div className="mt-4 rounded-xl border border-slate-200 bg-white p-4"><div className="text-xs font-black">Human approval</div><div className="mt-1 text-xs text-slate-500">Sourcing stays locked until the JD is explicitly approved.</div><div className="mt-3 flex flex-wrap gap-2">{jdApproval?.status==='approved'?<span className="inline-flex items-center gap-1 rounded-lg bg-emerald-100 px-3 py-2 text-xs font-black text-emerald-700"><Check className="h-4 w-4"/>JD approved</span>:<button onClick={()=>jdApproval?.id?approve(jdApproval.id):requestApproval('jd_approval')} disabled={loading} className="rounded-lg bg-violet-600 px-4 py-2.5 text-xs font-black text-white">{jdApproval?.status==='pending'?'Approve JD':'Request JD approval'}</button>}<button onClick={openSource} disabled={jdApproval?.status!=='approved'} className="rounded-lg border border-slate-200 px-4 py-2.5 text-xs font-black disabled:opacity-40">Continue to sourcing</button></div></div></div></Card>}
 {stage==='source'&&<Card title="Source candidates" sub={`Playwright browser workflow · ${source==='linkedin'?'LinkedIn':'Naukri'} · public profile evidence required`}><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-2xl font-black">{candidates.length}</span><span className="ml-2 text-sm text-slate-500">profiles captured</span></div><div className="flex gap-2"><button onClick={openSource} className="rounded-lg border border-slate-200 px-4 py-2.5 text-xs font-black">Search again</button><Action onClick={scoreCandidates} disabled={!candidates.length||loading} text="Score & shortlist"/></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{candidates.map((c,i)=><div key={c.id||c.profileUrl||i} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-black">{c.name}</div><div className="text-xs text-slate-500">{c.headline||c.role||'Candidate'}</div></div><span className="rounded-full bg-violet-50 px-2 py-1 text-[9px] font-black text-violet-700">{c.source||'browser'}</span></div><p className="mt-3 text-xs leading-5 text-slate-600">{c.reason||c.summary||'Evidence captured from the public profile.'}</p><div className="mt-3 flex flex-wrap gap-2">{(c.evidence||[]).slice(0,3).map((x,j)=><span key={j} className="rounded-lg bg-slate-50 px-2 py-1 text-[9px] font-semibold text-slate-600">{x}</span>)}</div>{c.profileUrl&&<a href={c.profileUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-[10px] font-black text-violet-700">Open source profile →</a>}</div>)}</div></Card>}
 {stage==='screen'&&<Card title="Candidate intelligence" sub="Ranked against the same JD, with explainable evidence."><div className="space-y-3">{candidates.map((c,i)=><div key={c.id||i} className={`rounded-2xl border p-4 ${i===0?'border-violet-200 bg-violet-50/50':'border-slate-200 bg-white'}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex-1"><div className="text-sm font-black">#{i+1} {c.name}</div><div className="mt-1 text-xs text-slate-500">{c.headline||'Candidate'} · {c.location||'Location not supplied'}</div></div><div className="text-2xl font-black text-violet-700">{c.score?.overall||0}%</div><button onClick={()=>planInterview(c)} className="rounded-lg bg-slate-950 px-4 py-2 text-xs font-black text-white">Interview</button></div><div className="mt-3 grid gap-2 sm:grid-cols-3">{(c.score?.evidence||c.evidence||[]).slice(0,3).map((x:string,j:number)=><div key={j} className="rounded-lg bg-white p-2 text-[10px] text-slate-600">{x}</div>)}</div></div>)}</div></Card>}
 {stage==='interview'&&<Card title="Structured interview" sub={`Role-specific evidence collection · ${selected?.name||'candidate'}`}><div className="space-y-4">{questions.map((q,i)=><div key={q.id||i} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="text-sm font-black">Q{i+1}. {q.question}</div><textarea value={answers[i]||''} onChange={e=>saveAnswer(i,e.target.value)} rows={4} placeholder="Capture the candidate's answer and evidence…" className="mt-3 w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:ring-2 focus:ring-violet-500"/></div>)}</div><Action onClick={completeInterview} disabled={loading||!questions.length||!answers.some(Boolean)} text="Complete interview & prepare decision"/></Card>}
 {stage==='decision'&&<Card title="Decision intelligence" sub="Recommendation prepared from resume/profile evidence and interview evidence."><div className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><div className="text-xs font-black uppercase tracking-widest text-violet-700">Recommendation</div><div className="mt-2 text-2xl font-black">{decision?.recommendation||'Ready for human review'}</div><p className="mt-2 text-sm leading-6 text-slate-600">{decision?.reason||'Review the evidence before approving the hiring decision.'}</p></div><Approval action="decision" approval={decisionApproval} onRequest={()=>requestApproval('decision')} onApprove={()=>decisionApproval?.id&&approve(decisionApproval.id)} loading={loading}/>{decisionApproval?.status==='approved'&&<Action onClick={recommendComp} disabled={loading} text="Continue to compensation"/>}</Card>}
 {stage==='comp'&&<Card title="Compensation benchmark" sub="Candidate-specific recommendation with an explicit approval gate."><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="text-xs font-black text-slate-500">Recommended base</div><div className="mt-2 text-3xl font-black">₹{Number(comp?.recommendedBase||comp?.base||analysis?.compensationMin||0).toLocaleString('en-IN')}</div><div className="mt-2 text-xs text-slate-500">{comp?.rationale||'Recommendation uses role range and supplied internal comparables.'}</div></div><Approval action="compensation" approval={compApproval} onRequest={()=>requestApproval('compensation')} onApprove={()=>compApproval?.id&&approve(compApproval.id)} loading={loading}/>{compApproval?.status==='approved'&&<Action onClick={draftOffer} disabled={loading} text="Draft offer"/>}</Card>}
 {stage==='offer'&&<Card title="Offer workspace" sub="Offer is prepared, but sending remains human-controlled."><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="text-xs font-black text-slate-500">Candidate</div><div className="mt-1 text-lg font-black">{selected?.name}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Info k="Role" v={title}/><Info k="Base" v={`₹${Number(offer?.base||0).toLocaleString('en-IN')}`}/><Info k="Status" v={offer?.status||'draft'}/></div></div><Approval action="offer" approval={offerApproval} onRequest={()=>requestApproval('offer')} onApprove={()=>offerApproval?.id&&approve(offerApproval.id)} loading={loading}/><div className="mt-3 flex gap-2">{offerApproval?.status==='approved'&&<button onClick={()=>sendOffer('sent')} disabled={loading} className="rounded-lg bg-violet-600 px-4 py-2.5 text-xs font-black text-white">Send offer</button>}</div></Card>}
 {stage==='engagement'&&<Card title="Pre-boarding engagement" sub="Offer acceptance unlocks the engagement plan."><div className="space-y-2">{engagement.map((x:any,i)=><div key={i} className="rounded-xl border border-slate-200 bg-white p-4 text-sm">{typeof x==='string'?x:x.title||x.task||JSON.stringify(x)}</div>)}</div><Action onClick={onboardingPlan} disabled={loading} text="Create onboarding plan"/></Card>}
 {stage==='onboarding'&&<Card title="Onboarding" sub="Ready-to-execute plan for the new employee."><pre className="overflow-auto rounded-2xl bg-slate-950 p-5 text-xs leading-6 text-slate-100">{JSON.stringify(onboarding,null,2)}</pre></Card>}
 </main>{showKey&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Bring your own AI key</h2><button onClick={()=>setShowKey(false)}><X className="h-5 w-5"/></button></div><p className="mt-2 text-xs leading-5 text-slate-500">Your key is stored through the Smart Scout credential vault and is not placed in browser localStorage.</p><select value={provider} onChange={e=>setProvider(e.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm"><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select><input value={apiKey} onChange={e=>setApiKey(e.target.value)} type="password" placeholder="Paste API key" className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm"/><button onClick={connectAI} disabled={!apiKey.trim()||loading} className="mt-3 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-black text-white disabled:opacity-40">{loading?'Connecting…':'Connect securely'}</button></div></div>}{sourceOpen&&<BrowserSourceConnect source={source} setSource={setSource} query={sourceQuery} setQuery={setSourceQuery} onStart={runSource} loading={loading} onClose={()=>setSourceOpen(false)}/>}</div>
}
function Card({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6"><h1 className="text-2xl font-black tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{sub}</p></div>{children}</section>}
function Box({label,children}:{label:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">{label}</div><div className="mt-3">{children}</div></div>}
function Info({k,v}:{k:string;v:string}){return <div className="flex items-center justify-between gap-4 border-b border-slate-100 py-2 text-xs"><span className="text-slate-400">{k}</span><b className="text-right">{v}</b></div>}
function Action({onClick,disabled,text}:{onClick:()=>void;disabled?:boolean;text:string}){return <button onClick={onClick} disabled={disabled} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-xs font-black text-white disabled:opacity-40">{disabled&&<Loader2 className="h-4 w-4 animate-spin"/>}{text}<ChevronRight className="h-4 w-4"/></button>}
function Approval({action,approval,onRequest,onApprove,loading}:{action:string;approval:any;onRequest:()=>void;onApprove:()=>void;loading:boolean}){return <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="font-black">Human approval gate</div><p className="mt-1 text-xs leading-5 text-slate-600">Smart Scout prepares the evidence; a human owns the decision.</p>{approval?.status==='approved'?<div className="mt-3 inline-flex items-center gap-1 rounded-lg bg-emerald-100 px-3 py-2 text-xs font-black text-emerald-700"><Check className="h-4 w-4"/>{action} approved</div>:<div className="mt-3 flex flex-wrap gap-2">{approval?.status!=='pending'&&<button onClick={onRequest} disabled={loading} className="rounded-lg bg-violet-600 px-4 py-2.5 text-xs font-black text-white">Request approval</button>}{approval?.status==='pending'&&<button onClick={onApprove} disabled={loading} className="rounded-lg bg-emerald-600 px-4 py-2.5 text-xs font-black text-white">Approve</button>}</div>}</div>}
