import React, { useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Loader2, Mic, Search, Settings2, Sparkles, Target, Volume2, X } from 'lucide-react';

type Analysis={title?:string;description?:string;mustHave?:string[];niceToHave?:string[];location?:string;experienceMin?:number;experienceMax?:number;compensationMin?:number;compensationMax?:number;department?:string;competencies?:string[];responsibilities?:string[];interviewFocus?:string[];sourcingKeywords?:string[]};
type Candidate={name:string;headline?:string;location?:string;profileUrl?:string;source?:string;summary?:string;evidence?:string[];score?:any};
const headers={'content-type':'application/json','x-tenant-id':'demo-tenant'};
async function api(path:string,body:any){const r=await fetch(`/api/recruiting/${path}`,{method:'POST',headers,body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d;}

export default function JobIntelligence({onBack}:{onBack?:()=>void}){
 const [stage,setStage]=useState<'create'|'source'|'screen'|'interview'|'decision'|'comp'|'offer'>('create');
 const [prompt,setPrompt]=useState(''); const [title,setTitle]=useState(''); const [jd,setJd]=useState(''); const [analysis,setAnalysis]=useState<Analysis|null>(null); const [candidates,setCandidates]=useState<Candidate[]>([]); const [selected,setSelected]=useState<Candidate|null>(null); const [interviewQuestions,setInterviewQuestions]=useState<string[]>([]); const [answers,setAnswers]=useState<string[]>([]); const [comp,setComp]=useState<any>(null); const [offer,setOffer]=useState<any>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [showKey,setShowKey]=useState(false); const [key,setKey]=useState(''); const [connected,setConnected]=useState(false); const [listening,setListening]=useState(false);
 const steps=[['create','Create JD'],['source','Find candidates'],['screen','AI screening'],['interview','Audio interview'],['decision','Select'],['comp','Comp analysis'],['offer','Offer']];
 const detail=useMemo(()=>analysis?[analysis.department,analysis.location,analysis.experienceMin!=null?`${analysis.experienceMin}${analysis.experienceMax?`–${analysis.experienceMax}`:'+'} yrs`:null].filter(Boolean).join(' · '):'', [analysis]);
 async function connectKey(){setError('');setLoading(true);try{await api('ai/connect',{provider:'gemini',apiKey:key,model:'gemini-2.5-flash'});setConnected(true);setShowKey(false);setKey('');}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function createJD(){setError('');if(!prompt.trim())return;setLoading(true);try{const d=await api('jd/analyze',{text:prompt});setAnalysis(d);setTitle(d.title||'New role');setJd(d.description||prompt);setStage('source')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function source(){setError('');setLoading(true);try{const d=await api('source/search',{role:{title,description:jd,...analysis},limit:8});setCandidates(d.candidates||[]);setStage('screen');}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function scoreAll(){setError('');setLoading(true);try{const requirement={title,description:jd,mustHave:analysis?.mustHave||[],niceToHave:analysis?.niceToHave||[],location:analysis?.location,experienceMin:analysis?.experienceMin,experienceMax:analysis?.experienceMax,department:analysis?.department};const scored=[];for(const c of candidates){try{scored.push({...c,score:await api('candidate/score',{candidate:c,requirement})})}catch{scored.push(c)}}setCandidates(scored.sort((a,b)=>(b.score?.overall||0)-(a.score?.overall||0)));setStage('screen')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function prepareInterview(c:Candidate){setSelected(c);setAnswers([]);try{const d=await api('interview/plan',{role:title,competencies:analysis?.competencies||analysis?.interviewFocus||[]});setInterviewQuestions((d.questions||d||[]).map((q:any)=>typeof q==='string'?q:q.question).slice(0,5));}catch{setInterviewQuestions((analysis?.interviewFocus||['Tell me about your most relevant experience for this role.','Describe a difficult leadership challenge you solved.','What would you prioritize in your first 90 days?']).slice(0,3))}setStage('interview')}
 function speak(text:string){if('speechSynthesis'in window){window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(text))}}
 function listen(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setError('Audio input is not supported in this browser. You can type the answer instead.');return}const r=new SR();r.lang='en-IN';r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=(e:any)=>setAnswers(a=>[...a,e.results[0][0].transcript]);r.start()}
 async function selectCandidate(){if(!selected)return;setLoading(true);try{await api('decision',{role:{title,description:jd,...analysis},candidates:[{name:selected.name,score:selected.score,interviewScore:Math.min(100,70+answers.length*8),answers}],decision:'select'});setStage('comp')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function compAnalysis(){setLoading(true);try{const observations=[`Role: ${title}`,`Location: ${analysis?.location||'unspecified'}`,`Experience: ${analysis?.experienceMin||0}-${analysis?.experienceMax||''} years`,`Candidate: ${selected?.name}`,`Candidate score: ${selected?.score?.overall||0}`,`Expected compensation: ${selected?.expectedCompensation||'not provided'}`];const d=await api('compensation/recommend',{observations,internalComparable:{role:title,rangeMin:analysis?.compensationMin,rangeMax:analysis?.compensationMax}});setComp(d);setStage('offer')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function draftOffer(){setLoading(true);try{const d=await api('offer/draft',{candidateName:selected?.name,role:title,compensation:comp,recommendation:comp});setOffer(d)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <div className="min-h-screen bg-[#f8fafc] text-slate-900"><header className="sticky top-0 z-20 h-16 border-b border-slate-200 bg-white flex items-center px-5 sm:px-8"><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="w-4 h-4"/> Recruiting OS</button><div className="mx-4 h-5 w-px bg-slate-200"/><div className="font-extrabold">Smart Scout Hiring Flow</div><button onClick={()=>setShowKey(true)} className="ml-auto inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><Settings2 className="w-4 h-4"/>{connected?'Gemini connected':'Connect Gemini'}</button></header>
 <div className="border-b border-slate-200 bg-white"><div className="max-w-6xl mx-auto px-5 sm:px-8 py-4 flex gap-2 overflow-x-auto">{steps.map(([id,label],i)=><React.Fragment key={id}><div className={`shrink-0 flex items-center gap-2 text-xs font-bold ${stage===id?'text-violet-700':'text-slate-400'}`}><span className={`h-7 w-7 rounded-full flex items-center justify-center ${stage===id?'bg-violet-600 text-white':'bg-slate-100'}`}>{i+1}</span>{label}</div>{i<steps.length-1&&<ChevronRight className="w-4 h-4 text-slate-300 mt-1"/>}</React.Fragment>)}</div></div>
 <main className="max-w-6xl mx-auto p-5 sm:p-8">{stage==='create'&&<section className="max-w-4xl mx-auto"><div className="text-center pt-10"><div className="inline-flex items-center gap-2 rounded-full bg-violet-50 px-4 py-2 text-xs font-bold text-violet-700"><Sparkles className="w-4 h-4"/> Start with intent</div><h1 className="mt-5 text-4xl sm:text-5xl font-black tracking-tight">Who are you hiring?</h1><p className="mt-4 text-slate-500">Describe the person you need. Smart Scout turns your prompt into a hiring blueprint, then finds, screens and interviews candidates.</p></div><div className="mt-8 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={8} placeholder="I need a VP HR for a 1,500-person technology company in Gurgaon. They should have scaled organizations, built leadership teams and handled high-growth environments..." className="w-full resize-none rounded-2xl border-0 bg-slate-50 p-5 text-base leading-7 outline-none focus:ring-2 focus:ring-violet-500"/><div className="mt-4 flex justify-end"><button disabled={!prompt.trim()||loading} onClick={createJD} className="rounded-xl bg-violet-600 px-6 py-3 text-sm font-bold text-white disabled:opacity-40">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:'Create JD & hiring blueprint →'}</button></div></div></section>}
 {stage==='source'&&<FlowCard title={title||'New role'} subtitle={detail||'AI-generated hiring blueprint'}><div className="grid lg:grid-cols-2 gap-5"><div><h3 className="font-extrabold">Hiring blueprint</h3><p className="mt-3 text-sm leading-6 text-slate-600">{analysis?.description||jd}</p><div className="mt-5 flex flex-wrap gap-2">{(analysis?.mustHave||[]).map((x,i)=><span key={i} className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">✓ {x}</span>)}</div></div><div className="rounded-2xl bg-violet-50 p-6"><Search className="w-6 h-6 text-violet-600"/><h3 className="mt-3 text-xl font-black">Find real candidates</h3><p className="mt-2 text-sm text-violet-900/70">Gemini Search will discover public professional profiles from the web and return source evidence.</p><button onClick={source} disabled={loading} className="mt-5 rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white">{loading?'Searching…':'Find candidates'}</button></div></div></FlowCard>}
 {stage==='screen'&&<FlowCard title="Candidate intelligence" subtitle={`${candidates.length} candidates discovered for ${title}`}><div className="flex justify-end mb-4"><button onClick={scoreAll} disabled={loading||!candidates.length} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white">{loading?'Scoring…':'Score all candidates'}</button></div><div className="grid gap-3">{candidates.map((c,i)=><div key={c.profileUrl||c.name+i} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col md:flex-row md:items-start gap-4"><div className="h-11 w-11 rounded-xl bg-violet-50 text-violet-700 flex items-center justify-center font-black">{c.name.slice(0,1)}</div><div className="flex-1"><div className="font-extrabold">{c.name}</div><div className="text-xs text-slate-500">{c.headline} · {c.location}</div><p className="mt-2 text-sm text-slate-600">{c.summary}</p><div className="mt-3 flex flex-wrap gap-2">{(c.evidence||[]).slice(0,3).map((e,j)=><span key={j} className="rounded-lg bg-slate-50 px-2.5 py-1 text-[11px] text-slate-600">{e}</span>)}</div>{c.profileUrl&&<a href={c.profileUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-bold text-violet-600">View source ↗</a>}</div><div className="md:text-right"><div className="text-3xl font-black text-violet-700">{c.score?.overall??'—'}<span className="text-xs text-slate-400">/100</span></div><button onClick={()=>prepareInterview(c)} className="mt-3 rounded-xl bg-violet-600 px-4 py-2 text-xs font-bold text-white">Interview →</button></div></div></div>)}</div></FlowCard>}
 {stage==='interview'&&selected&&<FlowCard title={`Audio interview · ${selected.name}`} subtitle={`${title} · ${interviewQuestions.length} competency questions`}><div className="grid lg:grid-cols-[1fr_320px] gap-5"><div className="rounded-3xl bg-slate-950 text-white p-8"><div className="text-xs font-bold uppercase tracking-widest text-violet-300">AI interviewer</div><h2 className="mt-3 text-2xl font-black">Conversational candidate interview</h2><p className="mt-2 text-sm text-slate-400">Questions are generated from the role competencies. The browser microphone captures candidate answers.</p><div className="mt-8 rounded-2xl bg-white/5 p-5"><div className="text-xs text-slate-400">Question {Math.min(answers.length+1,interviewQuestions.length)} of {interviewQuestions.length}</div><div className="mt-2 text-lg font-bold">{interviewQuestions[answers.length]||'Interview complete.'}</div></div><div className="mt-5 flex gap-3"><button onClick={()=>speak(interviewQuestions[answers.length]||'Thank you.')} className="rounded-xl bg-white/10 px-4 py-3 text-sm font-bold"><Volume2 className="inline w-4 h-4 mr-2"/>Ask aloud</button>{answers.length<interviewQuestions.length&&<button onClick={listen} className={`rounded-xl px-5 py-3 text-sm font-bold ${listening?'bg-rose-500':'bg-violet-600'}`}><Mic className="inline w-4 h-4 mr-2"/>{listening?'Listening…':'Record answer'}</button>}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-extrabold">Interview evidence</h3>{answers.length?<div className="mt-4 space-y-3">{answers.map((a,i)=><div key={i} className="rounded-xl bg-slate-50 p-3 text-xs leading-5"><b>Q{i+1}</b> {a}</div>)}</div>:<p className="mt-3 text-sm text-slate-400">No answers captured yet.</p>}{answers.length>=interviewQuestions.length&&<button onClick={selectCandidate} disabled={loading} className="mt-5 w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">Select candidate →</button>}</div></div></FlowCard>}
 {stage==='comp'&&<FlowCard title="Compensation intelligence" subtitle={`What should we offer ${selected?.name}?`}><div className="max-w-3xl mx-auto rounded-3xl border border-slate-200 bg-white p-8 text-center"><Target className="mx-auto w-8 h-8 text-violet-600"/><h2 className="mt-4 text-3xl font-black">Candidate-specific offer recommendation</h2><p className="mt-3 text-sm text-slate-500">Combines role range, candidate strength, experience and internal comparable data.</p><button onClick={compAnalysis} disabled={loading} className="mt-6 rounded-xl bg-violet-600 px-6 py-3 text-sm font-bold text-white">{loading?'Analysing…':'Analyse compensation'}</button>{comp&&<pre className="mt-6 text-left whitespace-pre-wrap rounded-2xl bg-slate-50 p-5 text-sm">{JSON.stringify(comp,null,2)}</pre>}</div></FlowCard>}
 {stage==='offer'&&<FlowCard title="Offer" subtitle={`${selected?.name} · ${title}`}><div className="max-w-3xl mx-auto rounded-3xl border border-slate-200 bg-white p-8"><div className="text-xs font-bold uppercase tracking-widest text-violet-600">Recommended package</div><pre className="mt-5 whitespace-pre-wrap rounded-2xl bg-slate-50 p-5 text-sm">{JSON.stringify(comp,null,2)}</pre><button onClick={draftOffer} disabled={loading} className="mt-5 w-full rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">{loading?'Generating…':'Generate offer'}</button>{offer&&<pre className="mt-5 whitespace-pre-wrap rounded-2xl bg-emerald-50 p-5 text-sm text-emerald-900">{JSON.stringify(offer,null,2)}</pre>}</div></FlowCard>}
 {stage==='decision'&&null}
 {error&&<div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 </main>{showKey&&<div className="fixed inset-0 z-50 bg-slate-950/40 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-black">Connect Gemini</h2><p className="mt-1 text-xs text-slate-500">Your key is sent to the Smart Scout server over HTTPS and used for your recruiting requests.</p></div><button onClick={()=>setShowKey(false)}><X/></button></div><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="AIza..." className="mt-5 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"/><button onClick={connectKey} disabled={!key||loading} className="mt-4 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white">{loading?'Connecting…':'Connect Gemini'}</button><p className="mt-3 text-[11px] text-slate-400">For persistent production configuration, use the Hostinger Node.js environment variable <b>GEMINI_API_KEY</b>.</p></div></div>}</div>
}
function FlowCard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div><div className="mb-6"><div className="text-xs uppercase tracking-[.18em] font-bold text-violet-600">Hiring workflow</div><h1 className="mt-2 text-3xl font-black">{title}</h1><p className="mt-2 text-sm text-slate-500">{subtitle}</p></div>{children}</div>}
