import React,{useState}from'react';
import{ArrowRight,Check,ChevronRight,KeyRound,Play,ShieldCheck,Sparkles,Users}from'lucide-react';
import ByokWidget from'./ByokWidget';

const stages=[
 {name:'Intent',title:'Hiring command',text:'Describe the person you need in plain language. Smart Scout turns the command into a structured hiring context.',signals:['Role: VP HR','Location: Gurgaon','Scale: 1,500 employees']},
 {name:'JD',title:'Job blueprint',text:'AI generates the JD, success profile and observable requirements, then pauses for human review.',signals:['Must-haves extracted','Fairness check passed','Human approval required']},
 {name:'Source',title:'Evidence-backed sourcing',text:'Use browser-based LinkedIn or Naukri workflows. Candidate profiles must include a public URL, source attribution and concrete evidence.',signals:['LinkedIn / Naukri','Profile URL captured','Evidence attached']},
 {name:'Shortlist',title:'Candidate intelligence',text:'Candidates are ranked against the role with explainable signals, knockout criteria and side-by-side comparison.',signals:['Fit score','Knockout checks','Evidence comparison']},
 {name:'Interview',title:'Structured interview',text:'Generate role-specific questions, capture answers and collect interview evidence before a decision is prepared.',signals:['Competency questions','Answer persistence','Interview evidence']},
 {name:'Decision',title:'Human decision gate',text:'Smart Scout prepares the recommendation. A human approves the hiring decision before compensation and offer steps unlock.',signals:['Recommendation','Evidence trail','Human approval']},
 {name:'Offer',title:'Compensation → offer',text:'Benchmark the candidate-specific package, draft the offer and keep sending behind an explicit approval gate.',signals:['Comp benchmark','Offer draft','Approval before send']}
];

export default function LandingPageRelease({onStart}:{onStart:()=>void}){
 const[stage,setStage]=useState(0);const[sheet,setSheet]=useState(false);const current=stages[stage];
 return <div className="min-h-screen bg-[#fafbff] text-slate-950">
  <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center px-4 sm:px-6"><a href="/" aria-label="Smart Scout home"><img src="/brand/smartscout-logo.svg" alt="Smart Scout" className="h-10 w-auto"/></a><div className="ml-auto flex items-center gap-2"><button onClick={()=>setSheet(true)} className="hidden rounded-lg border border-slate-200 px-3 py-2 text-[11px] font-black sm:inline-flex"><Play className="mr-1.5 h-3.5 w-3.5"/>See the workflow</button><button onClick={onStart} className="rounded-lg bg-slate-950 px-4 py-2.5 text-[11px] font-black text-white">Start hiring</button></div></div></header>
  <ByokWidget placement="top"/>
  <main>
   <section className="border-b border-slate-200/80 bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 pb-12 pt-12 sm:px-6 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:pb-16 lg:pt-16"><div><div className="inline-flex items-center gap-2 rounded-full border border-violet-200 bg-violet-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.16em] text-violet-700"><Sparkles className="h-3.5 w-3.5"/>AI hiring operating system</div><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[.94] tracking-[-.055em] sm:text-6xl lg:text-[72px]">From hiring intent<br/><span className="text-violet-600">to the right hire.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-500 sm:text-lg">Smart Scout turns one hiring command into a connected workflow — role design, sourcing, evidence, interviews, decisions, compensation and offers — with humans in control.</p><div className="mt-6 flex flex-col gap-2.5 sm:flex-row"><button onClick={()=>setSheet(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-xs font-black text-white shadow-lg shadow-violet-200"><Play className="h-3.5 w-3.5 fill-current"/>See the magic demo</button><button onClick={onStart} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-5 py-3 text-xs font-black">Bring a real hiring need<ArrowRight className="h-3.5 w-3.5"/></button></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xl shadow-slate-200/50"><div className="flex items-center justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-violet-600">Fictional product simulation</div><div className="mt-1 text-sm font-black">VP HR · Gurgaon</div></div><span className="rounded-full bg-violet-50 px-2.5 py-1 text-[9px] font-black text-violet-700">DEMO DATA</span></div><div className="mt-5 flex gap-1 overflow-x-auto pb-1">{stages.map((s,i)=><button key={s.name} onClick={()=>setStage(i)} className={`shrink-0 rounded-lg px-3 py-2 text-[9px] font-black uppercase ${i===stage?'bg-violet-600 text-white':'bg-slate-50 text-slate-500'}`}>{String(i+1).padStart(2,'0')} {s.name}</button>)}</div><div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="text-[9px] font-black uppercase tracking-widest text-slate-400">Screen shown now</div><h2 className="mt-2 text-xl font-black">{current.title}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{current.text}</p><div className="mt-4 space-y-2">{current.signals.map(x=><div key={x} className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-[10px] font-bold text-slate-600"><span className="flex h-5 w-5 items-center justify-center rounded-md bg-emerald-100 text-emerald-700"><Check className="h-3 w-3"/></span>{x}</div>)}</div></div><div className="mt-4 flex items-center justify-between"><button disabled={!stage} onClick={()=>setStage(v=>v-1)} className="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-black disabled:opacity-30">Back</button><button onClick={()=>stage===stages.length-1?setSheet(true):setStage(v=>v+1)} className="inline-flex items-center gap-1.5 rounded-lg bg-slate-950 px-4 py-2 text-[10px] font-black text-white">{stage===stages.length-1?'Open full demo':'Next screen'}<ChevronRight className="h-3 w-3"/></button></div></div>
   </div></section>
   <section className="border-b border-slate-200/80 bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6"><div className="grid gap-3 sm:grid-cols-3"><Trust icon={<KeyRound/>} title="Bring your own AI" text="Use Gemini, OpenAI or Anthropic with your own key. AI usage stays on your provider account."/><Trust icon={<ShieldCheck/>} title="Evidence first" text="Candidate profiles carry source attribution, public profile URLs and concrete evidence before ranking."/><Trust icon={<Users/>} title="Human control" text="JD, decision, compensation and offer actions remain approval-driven. AI prepares; humans decide."/></div></div></section>
   <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="rounded-2xl border border-violet-200 bg-violet-50 p-6 sm:p-8"><div className="max-w-3xl"><div className="text-[10px] font-black uppercase tracking-[.2em] text-violet-700">Why it is different</div><h2 className="mt-2 text-3xl font-black tracking-tight">One hiring context. Every stage connected.</h2><p className="mt-3 text-sm leading-6 text-slate-600">The JD is the central hiring object. Every candidate, interview, decision and offer is tied back to the same role requirements and evidence trail.</p></div><button onClick={onStart} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-xs font-black text-white">Run a real hiring need<ArrowRight className="h-3.5 w-3.5"/></button></div></section>
  </main>
  {sheet&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/70 p-3 backdrop-blur-md" onClick={()=>setSheet(false)}><div className="w-full max-w-5xl overflow-hidden rounded-2xl bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-violet-600">Smart Scout · product simulation</div><div className="mt-1 text-sm font-black">Full hiring journey · fictional demo data</div></div><button onClick={()=>setSheet(false)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-black">Close</button></div><div className="grid lg:grid-cols-[210px_1fr]"><aside className="border-b border-slate-100 p-3 lg:border-b-0 lg:border-r">{stages.map((s,i)=><button key={s.name} onClick={()=>setStage(i)} className={`mb-1 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-[10px] font-black ${i===stage?'bg-violet-600 text-white':'text-slate-500 hover:bg-slate-50'}`}><span>{String(i+1).padStart(2,'0')}</span>{s.name}<ChevronRight className="ml-auto h-3 w-3"/></button>)}</aside><div className="p-6 sm:p-8"><div className="text-[9px] font-black uppercase tracking-widest text-violet-600">Screen {stage+1} of {stages.length}</div><h3 className="mt-2 text-2xl font-black">{current.title}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{current.text}</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{current.signals.map(x=><div key={x} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-100 text-violet-700"><Check className="h-4 w-4"/></div><div className="mt-3 text-xs font-black">{x}</div></div>)}</div><div className="mt-8 flex justify-between"><button disabled={!stage} onClick={()=>setStage(v=>v-1)} className="rounded-lg border border-slate-200 px-4 py-2 text-xs font-black disabled:opacity-30">Back</button><button onClick={()=>stage===stages.length-1?onStart():setStage(v=>v+1)} className="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2 text-xs font-black text-white">{stage===stages.length-1?'Use your own hiring need':'Next screen'}<ArrowRight className="h-3.5 w-3.5"/></button></div></div></div></div></div>}
 </div>
}
function Trust({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-50 text-violet-600">{icon}</div><div className="mt-3 text-xs font-black">{title}</div><p className="mt-1 text-[10px] leading-4 text-slate-500">{text}</p></div>}
