import React,{useState}from'react';
import{ArrowRight,Check,KeyRound,Play,ShieldCheck,Sparkles,WandSparkles}from'lucide-react';
import MagicHiringDemoReal from'./MagicHiringDemoReal';

const candidates=[{name:'Rhea Malhotra',role:'CHRO / VP People · Fintech',score:94,reason:'Scaled HR 900 → 2,400; led org redesign and transformation.'},{name:'Arjun Mehta',role:'SVP People · SaaS',score:91,reason:'Built global talent systems across a 1,800-person SaaS business.'},{name:'Nisha Kapoor',role:'HR Director · Consumer Tech',score:86,reason:'Strong HRBP and growth-stage evidence.'}];
export default function LandingPageV2({onUseOwn}:{onUseOwn:()=>void}){const[demoVisible,setDemoVisible]=useState(false);const openDemo=()=>{setDemoVisible(true);window.setTimeout(()=>document.getElementById('magic-demo')?.scrollIntoView({behavior:'smooth',block:'start'}),20)};return <div className="min-h-screen bg-white font-['Segoe_UI_Variable','Segoe_UI',Arial,sans-serif] text-[#242424]">
<header className="sticky top-0 z-40 border-b border-[#e1dfdd] bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center px-5 sm:px-8"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-sm bg-[#5b2be0] text-white"><Sparkles className="h-5 w-5"/></span><b className="text-sm tracking-tight">SMART SCOUT</b></div><nav className="ml-auto hidden items-center gap-7 text-xs font-semibold text-[#605e5c] md:flex"><a href="#product">Product</a><a href="#control">Why Smart Scout</a><a href="#magic-demo">Demo</a></nav><button onClick={onUseOwn} className="ml-6 rounded-sm bg-[#242424] px-4 py-2.5 text-xs font-semibold text-white">Start hiring</button></div></header>
<main>
<section className="border-b border-[#e1dfdd] bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 pb-14 pt-14 sm:px-8 sm:pt-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><div className="inline-flex items-center gap-2 border border-[#d8ccff] bg-[#f5f1ff] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.18em] text-[#5b2be0]"><WandSparkles className="h-3.5 w-3.5"/>AI hiring operating system</div><h1 className="mt-5 max-w-3xl text-5xl font-bold leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-[70px]">From hiring intent<br/><span className="text-[#5b2be0]">to the right hire.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#605e5c] sm:text-lg">Give Smart Scout a hiring need. It builds the role, finds talent, screens evidence, interviews the strongest candidates and prepares the decision — with you in control.</p><div className="mt-7 flex flex-col gap-2.5 sm:flex-row"><button onClick={openDemo} className="inline-flex items-center justify-center gap-2 rounded-sm bg-[#5b2be0] px-5 py-3 text-sm font-semibold text-white"><Play className="h-4 w-4 fill-current"/>See the real hiring run</button><button onClick={onUseOwn} className="inline-flex items-center justify-center gap-2 rounded-sm border border-[#d6d3d1] bg-white px-5 py-3 text-sm font-semibold">Bring a real hiring need <ArrowRight className="h-4 w-4"/></button></div></div><div className="border border-[#d6d3d1] bg-[#faf9f8] p-4 shadow-[0_12px_35px_rgba(0,0,0,.06)]"><div className="flex items-center justify-between"><div><div className="text-[9px] font-bold uppercase tracking-[.2em] text-[#5b2be0]">Live hiring run</div><div className="mt-1 text-sm font-bold">VP HR · Gurgaon</div></div><span className="text-[9px] font-bold text-[#107c10]">● WORKING</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Metric n="186" l="sourced"/><Metric n="42" l="high fit"/><Metric n="12" l="interviewed"/><Metric n="3" l="recommended"/></div><div className="mt-3 space-y-2">{candidates.slice(0,2).map(c=><Candidate key={c.name} c={c}/>)}</div><div className="mt-3 flex items-center gap-2 border border-[#e1dfdd] bg-white px-3 py-2 text-[10px] font-semibold text-[#605e5c]"><ShieldCheck className="h-3.5 w-3.5 text-[#5b2be0]"/>Every recommendation includes evidence and reasoning.</div></div></div></section>
<section className="border-b border-[#e1dfdd] bg-[#faf9f8]"><div className="mx-auto grid max-w-7xl gap-3 px-5 py-6 sm:grid-cols-3 sm:px-8"><Trust icon={<KeyRound/>} title="Bring your own AI" text="Use Gemini, OpenAI or Anthropic with your own key."/><Trust icon={<ShieldCheck/>} title="Transparent by design" text="See the work, evidence, sources and reasoning."/><Trust icon={<Check/>} title="Human in control" text="AI does the work. You approve important decisions."/></div></section>
<section id="product" className="mx-auto max-w-7xl px-5 py-14 sm:px-8"><div className="max-w-3xl"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-[#5b2be0]">The product</div><h2 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">One hiring context. Every stage connected.</h2><p className="mt-3 text-sm leading-6 text-[#605e5c]">The demo below is built as product UI, not a slideshow: every stage changes the simulated application screen.</p></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card title="Role" text="Intent → JD → approval"/><Card title="Talent" text="Naukri + LinkedIn research"/><Card title="Evidence" text="Scores, reasons and interview signals"/><Card title="Outcome" text="Decision → comp → offer"/></div></section>
<section id="control" className="border-y border-[#242424] bg-[#242424] text-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-14 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="text-[10px] font-bold uppercase tracking-[.2em] text-[#b9a4ff]">Why Smart Scout</div><h2 className="mt-2 text-3xl font-bold sm:text-4xl">AI does the work.<br/>You see the work.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-[#c8c6c4]">No mystery scores. No silent hiring decisions. Smart Scout keeps the context connected and makes important evidence visible.</p><button onClick={onUseOwn} className="mt-6 rounded-sm bg-white px-5 py-3 text-sm font-semibold text-[#242424]">Start with a real role <ArrowRight className="ml-1 inline h-4 w-4"/></button></div><div className="grid gap-2 sm:grid-cols-2"><Dark title="Your AI" text="Bring your own provider and API key."/><Dark title="Your evidence" text="Source attribution, candidate signals and interview evidence."/><Dark title="Your approvals" text="JD, decision, compensation and offer gates stay human-controlled."/><Dark title="Your cost" text="AI usage remains with your chosen provider."/></div></div></section>
{demoVisible&&<MagicHiringDemoReal onUseOwn={onUseOwn}/>}<section className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="flex flex-col justify-between gap-4 border border-[#d8ccff] bg-[#f5f1ff] p-6 sm:flex-row sm:items-center"><div><div className="text-[10px] font-bold uppercase tracking-[.2em] text-[#5b2be0]">Ready when you are</div><div className="mt-1 text-xl font-bold">Bring the hiring need. Smart Scout takes it from there.</div></div><button onClick={onUseOwn} className="rounded-sm bg-[#5b2be0] px-5 py-3 text-sm font-semibold text-white">Start hiring <ArrowRight className="ml-1 inline h-4 w-4"/></button></div></section>
</main></div>}
function Metric({n,l}:{n:string;l:string}){return <div className="border border-[#e1dfdd] bg-white p-3"><div className="text-lg font-bold">{n}</div><div className="text-[9px] font-semibold uppercase tracking-wider text-[#797775]">{l}</div></div>}
function Candidate({c}:{c:typeof candidates[number]}){return <div className="border border-[#e1dfdd] bg-white p-3"><div className="flex gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-sm bg-[#242424] text-[9px] font-bold text-white">{c.name.split(' ').map(x=>x[0]).join('')}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b className="text-[11px]">{c.name}</b><span className="text-[10px] font-bold text-[#107c10]">{c.score}%</span></div><div className="text-[9px] text-[#797775]">{c.role}</div><div className="mt-1 text-[9px] leading-4 text-[#605e5c]">{c.reason}</div></div></div></div>}
function Trust({icon,title,text}:{icon:React.ReactElement;title:string;text:string}){return <div className="border border-[#e1dfdd] bg-white p-4"><span className="flex h-8 w-8 items-center justify-center rounded-sm bg-[#f5f1ff] text-[#5b2be0]">{React.cloneElement(icon,{className:'h-4 w-4'})}</span><div className="mt-3 text-xs font-bold">{title}</div><p className="mt-1 text-[10px] leading-4 text-[#605e5c]">{text}</p></div>}
function Card({title,text}:{title:string;text:string}){return <div className="border border-[#e1dfdd] bg-white p-4"><div className="text-xs font-bold">{title}</div><div className="mt-1 text-[10px] leading-4 text-[#605e5c]">{text}</div></div>}
function Dark({title,text}:{title:string;text:string}){return <div className="border border-white/10 bg-white/[.05] p-4"><div className="text-xs font-bold">{title}</div><div className="mt-1 text-[10px] leading-4 text-[#c8c6c4]">{text}</div></div>}
