import React from 'react';
import { Check, ChevronRight, FileText, KeyRound, Mic, Search, ShieldCheck, UserRound, Users, Video } from 'lucide-react';

export default function MagicDemoScreen({ stage }: { stage: number }) {
  const screens = [
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-[9px] font-black uppercase tracking-widest text-violet-600">Recruiter command</span><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black text-emerald-700">UNDERSTOOD</span></div><div className="mt-3 rounded-xl border border-violet-200 bg-violet-50 p-4 text-sm font-bold leading-6">Hire a VP HR for a 1,500-person technology company in Gurgaon.</div><div className="mt-3 grid grid-cols-3 gap-2"><Metric label="Role" value="VP HR"/><Metric label="Scale" value="1,500"/><Metric label="Location" value="Gurgaon"/></div></div>,
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-violet-600"/><span className="text-[9px] font-black uppercase tracking-widest text-violet-600">Job blueprint</span></div><div className="mt-3 text-lg font-black">VP HR · Gurgaon</div><p className="mt-1 text-xs leading-5 text-slate-500">Build the people function, lead transformation and partner with the CEO.</p><div className="mt-4 space-y-2">{['HR leadership experience','Org transformation','Executive partnering'].map(x=><div key={x} className="flex items-center gap-2 rounded-lg bg-emerald-50 px-3 py-2 text-[10px] font-bold text-emerald-800"><Check className="h-3.5 w-3.5"/>{x}</div>)}</div><div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-[10px] font-bold text-amber-800">Human approval required before sourcing</div></div>,
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Search className="h-5 w-5 text-violet-600"/><span className="text-[9px] font-black uppercase tracking-widest text-violet-600">Browser sourcing</span></div><span className="text-[9px] font-black text-emerald-600">HUMAN HANDOFF</span></div><div className="mt-3 flex gap-2"><span className="rounded-lg bg-[#0a66c2] px-3 py-2 text-[10px] font-black text-white">LinkedIn</span><span className="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-black">Naukri</span></div><div className="mt-3 rounded-xl bg-slate-50 p-3"><div className="text-[9px] font-black uppercase text-slate-400">Search</div><div className="mt-1 text-xs font-bold">VP HR Gurgaon fintech technology</div></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Candidate name="Aarav Mehta" score="94%"/><Candidate name="Riya Kapoor" score="91%"/></div></div>,
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-violet-600"/><span className="text-[9px] font-black uppercase tracking-widest text-violet-600">Candidate intelligence</span></div><span className="rounded-full bg-violet-50 px-2 py-1 text-[9px] font-black text-violet-700">42 HIGH FIT</span></div><div className="mt-4 grid gap-2"><CompareRow name="Aarav Mehta" score="94" evidence="Org redesign · 1,200 staff"/><CompareRow name="Riya Kapoor" score="91" evidence="HR transformation · fintech"/><CompareRow name="Kabir Shah" score="87" evidence="Leadership · scale-up"/></div></div>,
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><Video className="h-5 w-5 text-violet-600"/><span className="text-[9px] font-black uppercase tracking-widest text-violet-600">Structured interview</span></div><div className="mt-3 rounded-xl bg-slate-950 p-4 text-white"><div className="text-[9px] font-black uppercase tracking-widest text-violet-300">Question 03 · Org design</div><div className="mt-2 text-sm font-bold leading-5">Tell us about a transformation you led and how you measured the outcome.</div></div><div className="mt-3 rounded-xl border border-slate-200 p-3"><div className="flex items-center gap-2 text-[10px] font-black"><Mic className="h-4 w-4 text-violet-600"/>Evidence captured</div><div className="mt-1 text-[10px] text-slate-500">Answer persisted · competency mapped · concern check ready</div></div></div>,
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-violet-600"/><span className="text-[9px] font-black uppercase tracking-widest text-violet-600">Decision brief</span></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-black text-amber-700">AWAITING HUMAN DECISION</span></div><div className="mt-3 text-lg font-black">Recommend: Hire</div><div className="mt-3 grid grid-cols-3 gap-2"><Metric label="Role fit" value="94%"/><Metric label="Interview" value="92%"/><Metric label="Evidence" value="18"/></div><div className="mt-3 rounded-xl bg-emerald-50 p-3 text-[10px] font-bold text-emerald-800">Strengths: transformation leadership, scale, executive partnership</div></div>,
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-violet-600"/><span className="text-[9px] font-black uppercase tracking-widest text-violet-600">Compensation → offer</span></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><div className="text-[9px] font-black uppercase text-slate-400">Recommended base</div><div className="mt-1 text-xl font-black">₹72L</div></div><div className="rounded-xl bg-slate-50 p-3"><div className="text-[9px] font-black uppercase text-slate-400">Variable</div><div className="mt-1 text-xl font-black">20%</div></div></div><div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-[10px] font-bold text-amber-800">Offer is drafted. Human approval is required before sending.</div></div>
  ];
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-slate-50 shadow-inner"><div className="flex items-center gap-1 border-b border-slate-200 bg-white px-3 py-2"><span className="h-2 w-2 rounded-full bg-rose-300"/><span className="h-2 w-2 rounded-full bg-amber-300"/><span className="h-2 w-2 rounded-full bg-emerald-300"/><div className="ml-3 h-5 flex-1 rounded-md bg-slate-100"/><ChevronRight className="h-3 w-3 text-slate-300"/></div><div className="p-3 sm:p-5">{screens[stage]||screens[0]}</div></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-slate-200 bg-white p-2"><div className="text-[8px] font-black uppercase text-slate-400">{label}</div><div className="mt-1 text-[11px] font-black">{value}</div></div>}
function Candidate({name,score}:{name:string;score:string}){return <div className="flex items-center gap-2 rounded-lg border border-slate-200 p-2"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-violet-100 text-violet-700"><UserRound className="h-3.5 w-3.5"/></span><div className="min-w-0 flex-1"><div className="truncate text-[10px] font-black">{name}</div><div className="text-[8px] text-slate-400">Public profile · evidence</div></div><b className="text-[10px] text-emerald-600">{score}</b></div>}
function CompareRow({name,score,evidence}:{name:string;score:string;evidence:string}){return <div className="grid grid-cols-[1fr_auto] gap-2 rounded-xl border border-slate-200 p-3"><div><div className="text-[10px] font-black">{name}</div><div className="mt-1 text-[9px] text-slate-500">{evidence}</div></div><div className="text-right"><div className="text-lg font-black text-violet-700">{score}</div><div className="text-[8px] font-bold text-slate-400">FIT</div></div></div>}
