import { createClient } from '@supabase/supabase-js';

export type AuditEventInput = { tenantId:string; workflowId?:string|null; candidateId?:string|null; eventType:string; actorType?:string; actorId?:string|null; provider?:string|null; model?:string|null; evidence?:unknown[]; payload?:Record<string,unknown> };
const MAX_AUDIT_PAYLOAD_BYTES = 64 * 1024;
const MAX_AUDIT_EVIDENCE_BYTES = 64 * 1024;
const MAX_AUDIT_EVENT_TYPE_LENGTH = 128;
const MAX_AUDIT_IDENTITY_LENGTH = 128;
function db(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;return url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null}
function uuid(value?:string|null){if(!value)return null;return value.startsWith('job_')||value.startsWith('candidate_')?value.slice(value.indexOf('_')+1):value}
function requireAuditIdentity(input:Pick<AuditEventInput,'tenantId'|'eventType'>){if(!input.tenantId?.trim())throw new Error('Audit event tenantId is required');if(!input.eventType?.trim())throw new Error('Audit event eventType is required');if(input.eventType.trim().length>MAX_AUDIT_EVENT_TYPE_LENGTH)throw new Error(`Audit event eventType exceeds ${MAX_AUDIT_EVENT_TYPE_LENGTH} characters`)}
function requireOptionalIdentity(name:string,value?:string|null){if(value !== undefined && value !== null){if(!value.trim())throw new Error(`Audit event ${name} is required when provided`);if(value.trim().length>MAX_AUDIT_IDENTITY_LENGTH)throw new Error(`Audit event ${name} exceeds ${MAX_AUDIT_IDENTITY_LENGTH} characters`)}}
function serializeWithinBoundary(name:string,value:unknown,maxBytes:number){let serialized:string;try{serialized=JSON.stringify(value)}catch{throw new Error(`Audit event ${name} must be JSON serializable`)}if(Buffer.byteLength(serialized,'utf8')>maxBytes)throw new Error(`Audit event ${name} exceeds ${maxBytes} bytes`)}
function requirePayloadBoundary(payload?:Record<string,unknown>){if(payload === undefined || payload === null)return;serializeWithinBoundary('payload',payload,MAX_AUDIT_PAYLOAD_BYTES)}
function requireEvidenceBoundary(evidence?:unknown[]){if(evidence === undefined || evidence === null)return;if(!Array.isArray(evidence))throw new Error('Audit event evidence must be an array');serializeWithinBoundary('evidence',evidence,MAX_AUDIT_EVIDENCE_BYTES)}
export async function recordAuditEvent(input:AuditEventInput){requireAuditIdentity(input);requireOptionalIdentity('workflowId',input.workflowId);requireOptionalIdentity('candidateId',input.candidateId);requireOptionalIdentity('actorId',input.actorId);requireOptionalIdentity('actorType',input.actorType);requireOptionalIdentity('provider',input.provider);requireOptionalIdentity('model',input.model);requirePayloadBoundary(input.payload);requireEvidenceBoundary(input.evidence);const client=db();if(!client)return{persisted:false};const{data,error}=await client.from('recruiting_audit_events').insert({tenant_id:input.tenantId,workflow_id:uuid(input.workflowId),candidate_id:uuid(input.candidateId),event_type:input.eventType,actor_type:input.actorType||'system',actor_id:input.actorId||null,provider:input.provider||null,model:input.model||null,evidence:input.evidence||[],payload:input.payload||{}}).select('*').single();if(error)throw new Error(`Unable to persist audit event: ${error.message}`);return{persisted:true,event:data}}
export async function listAuditEvents(tenantId:string,workflowId?:string|null){if(!tenantId?.trim())throw new Error('Audit event tenantId is required');requireOptionalIdentity('workflowId',workflowId);const client=db();if(!client)return[];let query=client.from('recruiting_audit_events').select('*').eq('tenant_id',tenantId).order('created_at',{ascending:false}).limit(500);if(workflowId)query=query.eq('workflow_id',uuid(workflowId));const{data,error}=await query;if(error)throw new Error(`Unable to load audit events: ${error.message}`);return data||[]}
export async function countAuditEvents(tenantId:string,workflowId?:string|null){if(!tenantId?.trim())throw new Error('Audit event tenantId is required');requireOptionalIdentity('workflowId',workflowId);const client=db();if(!client)return{configured:false,count:0};let query=client.from('recruiting_audit_events').select('id',{count:'exact',head:true}).eq('tenant_id',tenantId);if(workflowId)query=query.eq('workflow_id',uuid(workflowId));const{count,error}=await query;if(error)throw new Error(`Unable to count audit events: ${error.message}`);return{configured:true,count:count||0}}
