import { promises as fs } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { audit } from './controlPlane.js';

export type SavedCandidate = { id:string; tenantId:string; jobId:string; candidate:any; score?:any; createdAt:string; updatedAt:string };
const filePath=process.env.SMARTSCOUT_CANDIDATE_STORE||path.join(process.cwd(),'.smartscout-candidates.json');
let writeQueue=Promise.resolve();
function db(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;return url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null}
function requireTenantId(tenantId:string){if(!tenantId?.trim())throw new Error('tenantId is required');return tenantId.trim()}
function workflowUuid(id:string){return id.startsWith('job_')?id.slice(4):id}
function publicCandidate(row:any):SavedCandidate{return{id:`candidate_${row.id}`,tenantId:row.tenant_id,jobId:`job_${row.workflow_id}`,candidate:{id:`candidate_${row.id}`,name:row.name,email:row.email,phone:row.phone,profileUrl:row.profile_url,source:row.source,resumeText:row.resume_text,evidence:row.evidence,status:row.status},score:row.score,createdAt:row.created_at,updatedAt:row.updated_at}}
async function readAll():Promise<SavedCandidate[]>{try{return JSON.parse(await fs.readFile(filePath,'utf8'))}catch{return[]}}
export async function saveCandidates(tenantId:string,jobId:string,candidates:any[]):Promise<SavedCandidate[]>{
 tenantId=requireTenantId(tenantId);
 const normalizedJobId=requiredJobId(jobId);
 const client=db();
 if(client){const workflowId=workflowUuid(normalizedJobId);const rows=candidates.map(c=>({tenant_id:tenantId,workflow_id:workflowId,name:c.name||'Unknown candidate',email:c.email||null,phone:c.phone||null,profile_url:c.profileUrl||c.profile_url||null,source:c.source||'browser',resume_text:c.resumeText||c.resume_text||null,score:c.score||null,status:c.status||'discovered',evidence:c.evidence||[]}));const {data,error}=await client.from('recruiting_candidates').insert(rows).select('*');if(error)throw new Error(`Unable to persist candidates: ${error.message}`);const saved=(data||[]).map(publicCandidate);await audit({tenantId,jobId:normalizedJobId,action:'candidates_persisted',actor:'system',metadata:{count:saved.length,candidateIds:saved.map(c=>c.id)}});return saved}
 const now=new Date().toISOString();const saved=candidates.map(candidate=>({id:`candidate_${crypto.randomUUID()}`,tenantId,jobId:normalizedJobId,candidate,createdAt:now,updatedAt:now}));writeQueue=writeQueue.then(async()=>{const all=await readAll(),kept=all.filter(x=>!(x.tenantId===tenantId&&x.jobId===normalizedJobId));await fs.writeFile(filePath,JSON.stringify([...saved,...kept].slice(0,5000),null,2),'utf8')});await writeQueue;await audit({tenantId,jobId:normalizedJobId,action:'candidates_persisted',actor:'system',metadata:{count:saved.length,candidateIds:saved.map(c=>c.id)}});return saved;
}
function requiredJobId(jobId:string){const normalized=String(jobId??'').trim();if(!normalized)throw new Error('jobId is required');if(normalized.length>256)throw new Error('jobId is too long');return normalized}
function requiredStatus(status:string){const normalized=String(status??'').trim();if(!normalized)throw new Error('status is required');if(normalized.length>64)throw new Error('status is too long');return normalized}
export async function listCandidates(tenantId:string,jobId:string):Promise<SavedCandidate[]>{tenantId=requireTenantId(tenantId);const normalizedJobId=requiredJobId(jobId);const client=db();if(client){const {data,error}=await client.from('recruiting_candidates').select('*').eq('tenant_id',tenantId).eq('workflow_id',workflowUuid(normalizedJobId)).order('updated_at',{ascending:false});if(error)throw new Error(`Unable to list candidates: ${error.message}`);return(data||[]).map(publicCandidate)}return(await readAll()).filter(x=>x.tenantId===tenantId&&x.jobId===normalizedJobId)}
export async function updateCandidateStatus(tenantId:string,id:string,status:string):Promise<SavedCandidate|null>{tenantId=requireTenantId(tenantId);const candidateId=String(id??'').trim();if(!candidateId)throw new Error('candidateId is required');const normalizedStatus=requiredStatus(status);const client=db();if(client){const databaseId=candidateId.startsWith('candidate_')?candidateId.slice(10):candidateId;const {data,error}=await client.from('recruiting_candidates').update({status:normalizedStatus,updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',databaseId).select('*').maybeSingle();if(error)throw new Error(`Unable to update candidate status: ${error.message}`);const updated=data?publicCandidate(data):null;if(updated)await audit({tenantId,jobId:updated.jobId,candidateId:updated.id,action:'candidate_status_updated',actor:'system',metadata:{status:normalizedStatus}});return updated}let result:SavedCandidate|null=null;writeQueue=writeQueue.then(async()=>{const all=await readAll(),index=all.findIndex(x=>x.tenantId===tenantId&&x.id===candidateId);if(index<0){result=null;return}result={...all[index],candidate:{...all[index].candidate,status:normalizedStatus},updatedAt:new Date().toISOString()};all[index]=result;await fs.writeFile(filePath,JSON.stringify(all,null,2),'utf8')});await writeQueue;if(result)await audit({tenantId,jobId:result.jobId,candidateId:result.id,action:'candidate_status_updated',actor:'system',metadata:{status:normalizedStatus}});return result}
export async function updateCandidateScore(tenantId:string,id:string,score:any):Promise<SavedCandidate|null>{tenantId=requireTenantId(tenantId);const candidateId=String(id??'').trim();if(!candidateId)throw new Error('candidateId is required');const client=db();if(client){const databaseId=candidateId.startsWith('candidate_')?candidateId.slice(10):candidateId;const {data,error}=await client.from('recruiting_candidates').update({score,updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',databaseId).select('*').maybeSingle();if(error)throw new Error(`Unable to update candidate score: ${error.message}`);const updated=data?publicCandidate(data):null;if(updated)await audit({tenantId,jobId:updated.jobId,candidateId:updated.id,action:'candidate_score_updated',actor:'system',metadata:{score}});return updated}let result:SavedCandidate|null=null;writeQueue=writeQueue.then(async()=>{const all=await readAll(),index=all.findIndex(x=>x.tenantId===tenantId&&x.id===candidateId);if(index<0){result=null;return}result={...all[index],score,updatedAt:new Date().toISOString()};all[index]=result;await fs.writeFile(filePath,JSON.stringify(all,null,2),'utf8')});await writeQueue;if(result)await audit({tenantId,jobId:result.jobId,candidateId:result.id,action:'candidate_score_updated',actor:'system',metadata:{score}});return result}
