import { promises as fs } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { audit } from './controlPlane.js';

export type SavedCandidate = { id:string; tenantId:string; jobId:string; candidate:any; score?:any; createdAt:string; updatedAt:string };
const filePath=process.env.SMARTSCOUT_CANDIDATE_STORE||path.join(process.cwd(),'.smartscout-candidates.json');
const MAX_CANDIDATES_PER_BATCH=5000;
const MAX_IDENTIFIER_LENGTH=256;
let writeQueue=Promise.resolve();
function db(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;return url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null}
function requireTenantId(tenantId:string){const normalized=String(tenantId??'').trim();if(!normalized)throw new Error('tenantId is required');if(normalized.length>MAX_IDENTIFIER_LENGTH)throw new Error('tenantId is too long');return normalized}
function workflowUuid(id:string){return id.startsWith('job_')?id.slice(4):id}
function publicCandidate(row:any):SavedCandidate{return{id:`candidate_${row.id}`,tenantId:row.tenant_id,jobId:`job_${row.workflow_id}`,candidate:{id:`candidate_${row.id}`,name:row.name,email:row.email,phone:row.phone,profileUrl:row.profile_url,source:row.source,resumeText:row.resume_text,evidence:row.evidence,status:row.status},score:row.score,createdAt:row.created_at,updatedAt:row.updated_at}}
async function readAll():Promise<SavedCandidate[]>{try{return JSON.parse(await fs.readFile(filePath,'utf8'))}catch{return[]}}
function requiredJobId(jobId:string){const normalized=String(jobId??'').trim();if(!normalized)throw new Error('jobId is required');if(normalized.length>MAX_IDENTIFIER_LENGTH)throw new Error('jobId is too long');return normalized}
function requiredCandidateBatch(candidates:any[]){if(!Array.isArray(candidates))throw new Error('candidates must be an array');if(candidates.length>MAX_CANDIDATES_PER_BATCH)throw new Error(`candidate batch is too large; maximum is ${MAX_CANDIDATES_PER_BATCH}`);if(candidates.some(candidate=>!candidate||typeof candidate!=='object'||Array.isArray(candidate)))throw new Error('candidate entries must be objects');return candidates}
function requiredCandidateId(id:string){const normalized=String(id??'').trim();if(!normalized)throw new Error('candidateId is required');if(normalized.length>MAX_IDENTIFIER_LENGTH)throw new Error('candidateId is too long');return normalized}
function requiredStatus(status:string){const normalized=String(status??'').trim();if(!normalized)throw new Error('status is required');if(normalized.length>64)throw new Error('status is too long');return normalized}
function sameScore(left:any,right:any){return JSON.stringify(left)===JSON.stringify(right)}
export async function saveCandidates(tenantId:string,jobId:string,candidates:any[]):Promise<SavedCandidate[]>{
 tenantId=requireTenantId(tenantId);
 const normalizedJobId=requiredJobId(jobId);
 const normalizedCandidates=requiredCandidateBatch(candidates);
 const client=db();
 if(client){const workflowId=workflowUuid(normalizedJobId);const rows=normalizedCandidates.map(c=>({tenant_id:tenantId,workflow_id:workflowId,name:c.name||'Unknown candidate',email:c.email||null,phone:c.phone||null,profile_url:c.profileUrl||c.profile_url||null,source:c.source||'browser',resume_text:c.resumeText||c.resume_text||null,score:c.score||null,status:c.status||'discovered',evidence:c.evidence||[]}));const {data,error}=await client.from('recruiting_candidates').insert(rows).select('*');if(error)throw new Error(`Unable to persist candidates: ${error.message}`);const saved=(data||[]).map(publicCandidate);await audit({tenantId,jobId:normalizedJobId,action:'candidates_persisted',actor:'system',metadata:{count:saved.length,candidateIds:saved.map(c=>c.id)}});return saved}
 const now=new Date().toISOString();const saved=normalizedCandidates.map(candidate=>({id:`candidate_${crypto.randomUUID()}`,tenantId,jobId:normalizedJobId,candidate,createdAt:now,updatedAt:now}));writeQueue=writeQueue.then(async()=>{const all=await readAll(),kept=all.filter(x=>!(x.tenantId===tenantId&&x.jobId===normalizedJobId));await fs.writeFile(filePath,JSON.stringify([...saved,...kept].slice(0,5000),null,2),'utf8')});await writeQueue;await audit({tenantId,jobId:normalizedJobId,action:'candidates_persisted',actor:'system',metadata:{count:saved.length,candidateIds:saved.map(c=>c.id)}});return saved;
}
export async function listCandidates(tenantId:string,jobId:string):Promise<SavedCandidate[]>{tenantId=requireTenantId(tenantId);const normalizedJobId=requiredJobId(jobId);const client=db();if(client){const {data,error}=await client.from('recruiting_candidates').select('*').eq('tenant_id',tenantId).eq('workflow_id',workflowUuid(normalizedJobId)).order('updated_at',{ascending:false});if(error)throw new Error(`Unable to list candidates: ${error.message}`);return(data||[]).map(publicCandidate)}return(await readAll()).filter(x=>x.tenantId===tenantId&&x.jobId===normalizedJobId)}
export async function updateCandidateStatus(tenantId:string,id:string,status:string):Promise<SavedCandidate|null>{tenantId=requireTenantId(tenantId);const candidateId=requiredCandidateId(id);const normalizedStatus=requiredStatus(status);const client=db();if(client){const databaseId=candidateId.startsWith('candidate_')?candidateId.slice(10):candidateId;const {data:before,error:beforeError}=await client.from('recruiting_candidates').select('*').eq('tenant_id',tenantId).eq('id',databaseId).maybeSingle();if(beforeError)throw new Error(`Unable to read candidate status: ${beforeError.message}`);if(!before)return null;const previousStatus=before.status;if(previousStatus===normalizedStatus)return publicCandidate(before);const {data,error}=await client.from('recruiting_candidates').update({status:normalizedStatus,updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',databaseId).eq('status',previousStatus).select('*').maybeSingle();if(error)throw new Error(`Unable to update candidate status: ${error.message}`);if(!data){const {data:current,error:currentError}=await client.from('recruiting_candidates').select('*').eq('tenant_id',tenantId).eq('id',databaseId).maybeSingle();if(currentError)throw new Error(`Unable to re-read candidate status: ${currentError.message}`);if(!current)return null;if(current.status===normalizedStatus)return publicCandidate(current);return publicCandidate(current)}const updated=publicCandidate(data);await audit({tenantId,jobId:updated.jobId,candidateId:updated.id,action:'candidate_status_updated',actor:'system',metadata:{previousStatus,nextStatus:normalizedStatus}});return updated}let result:SavedCandidate|null=null;let previousStatus:string|undefined;writeQueue=writeQueue.then(async()=>{const all=await readAll(),index=all.findIndex(x=>x.tenantId===tenantId&&x.id===candidateId);if(index<0){result=null;return}previousStatus=all[index].candidate?.status;if(previousStatus===normalizedStatus){result=all[index];return}result={...all[index],candidate:{...all[index].candidate,status:normalizedStatus},updatedAt:new Date().toISOString()};all[index]=result;await fs.writeFile(filePath,JSON.stringify(all,null,2),'utf8')});await writeQueue;if(result&&previousStatus!==normalizedStatus)await audit({tenantId,jobId:result.jobId,candidateId:result.id,action:'candidate_status_updated',actor:'system',metadata:{previousStatus,nextStatus:normalizedStatus}});return result}
export async function updateCandidateScore(tenantId:string,id:string,score:any):Promise<SavedCandidate|null>{tenantId=requireTenantId(tenantId);const candidateId=requiredCandidateId(id);const client=db();if(client){const databaseId=candidateId.startsWith('candidate_')?candidateId.slice(10):candidateId;const {data:before,error:beforeError}=await client.from('recruiting_candidates').select('*').eq('tenant_id',tenantId).eq('id',databaseId).maybeSingle();if(beforeError)throw new Error(`Unable to read candidate score: ${beforeError.message}`);if(!before)return null;const previousScore=before.score;if(sameScore(previousScore,score))return publicCandidate(before);const {data,error}=await client.from('recruiting_candidates').update({score,updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',databaseId).select('*').maybeSingle();if(error)throw new Error(`Unable to update candidate score: ${error.message}`);const updated=data?publicCandidate(data):null;if(updated)await audit({tenantId,jobId:updated.jobId,candidateId:updated.id,action:'candidate_score_updated',actor:'system',metadata:{previousScore,nextScore:score}});return updated}let result:SavedCandidate|null=null;let previousScore:any;writeQueue=writeQueue.then(async()=>{const all=await readAll(),index=all.findIndex(x=>x.tenantId===tenantId&&x.id===candidateId);if(index<0){result=null;return}previousScore=all[index].score;if(sameScore(previousScore,score)){result=all[index];return}result={...all[index],score,updatedAt:new Date().toISOString()};all[index]=result;await fs.writeFile(filePath,JSON.stringify(all,null,2),'utf8')});await writeQueue;if(result&&!sameScore(previousScore,score))await audit({tenantId,jobId:result.jobId,candidateId:result.id,action:'candidate_score_updated',actor:'system',metadata:{previousScore,nextScore:score}});return result}