import { promises as fs } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { Router } from 'express';
import { recordAuditEvent as persistAuditEvent } from './auditStore.js';

type RecordBase={id:string;tenantId:string;createdAt:string;updatedAt:string};
export type Approval=RecordBase&{jobId:string;candidateId?:string;action:'jd_approval'|'reject'|'decision'|'compensation'|'offer'|'employee_create';status:'pending'|'approved'|'rejected';requestedBy:string;decidedBy?:string;note?:string};
export type AuditEvent=RecordBase&{jobId?:string;candidateId?:string;action:string;actor:string;metadata?:Record<string,unknown>;persistence:'database'|'local-fallback'};
export type InterviewSchedule=RecordBase&{jobId:string;candidateId:string;startsAt:string;endsAt:string;timezone:string;mode:'ai_audio'|'human'|'panel';status:'proposed'|'confirmed'|'cancelled';candidateEmail?:string;interviewUrl?:string};
type ScheduleStatus=InterviewSchedule['status'];
export type UsageRecord=RecordBase&{period:string;feature:string;units:number;metadata?:Record<string,unknown>};
type ApprovalInput=Omit<Approval,'id'|'createdAt'|'updatedAt'|'status'>;type AuditInput=Omit<AuditEvent,'id'|'createdAt'|'updatedAt'|'persistence'>;type UsageInput=Omit<UsageRecord,'id'|'createdAt'|'updatedAt'>;
const root=process.env.SMARTSCOUT_CONTROL_PLANE_DIR||path.join(process.cwd(),'.smartscout-control-plane');const files={approvals:'approvals.json',audit:'audit.json',schedules:'schedules.json',usage:'usage.json'} as const;const queues:Record<string,Promise<void>>={};
async function read<T>(name:string):Promise<T[]>{try{return JSON.parse(await fs.readFile(path.join(root,name),'utf8'));}catch{return[];}}
async function append<T extends RecordBase>(name:string,value:T):Promise<T>{await fs.mkdir(root,{recursive:true});queues[name]=(queues[name]||Promise.resolve()).then(async()=>{const all=await read<T>(name);all.unshift(value);await fs.writeFile(path.join(root,name),JSON.stringify(all.slice(0,10000),null,2),'utf8')});await queues[name];return value;}
async function mutate<T>(name:string, fn:(all:T[])=>Promise<T>|T):Promise<T>{await fs.mkdir(root,{recursive:true});const prior=queues[name]||Promise.resolve();let result!:T;queues[name]=prior.then(async()=>{const all=await read<T>(name);result=await fn(all);await fs.writeFile(path.join(root,name),JSON.stringify(all,null,2),'utf8');});await queues[name];return result;}
const now=()=>new Date().toISOString();
const allowedScheduleTransitions:Record<ScheduleStatus,readonly ScheduleStatus[]>={proposed:['proposed','confirmed','cancelled'],confirmed:['confirmed','cancelled'],cancelled:['cancelled']};
export function isAllowedScheduleTransition(from:ScheduleStatus,to:ScheduleStatus){return allowedScheduleTransitions[from].includes(to);}
export async function audit(input:AuditInput):Promise<AuditEvent>{const t=now();const persisted=await persistAuditEvent({tenantId:input.tenantId,workflowId:input.jobId||null,candidateId:input.candidateId||null,eventType:input.action,actorType:input.actor,actorId:input.actor,payload:input.metadata||{}});const persistence:AuditEvent['persistence']=persisted.persisted?'database':'local-fallback';const value={...input,id:`audit_${crypto.randomUUID()}`,createdAt:t,updatedAt:t,persistence};await append(files.audit,value);return value;}
export async function requestApproval(input:ApprovalInput):Promise<Approval>{const t=now();const value:Approval={...input,id:`approval_${crypto.randomUUID()}`,createdAt:t,updatedAt:t,status:'pending'};await append(files.approvals,value);await audit({tenantId:input.tenantId,jobId:input.jobId,candidateId:input.candidateId,action:'approval_requested',actor:input.requestedBy,metadata:{approvalId:value.id,approvalAction:value.action}});return value;}
export async function decideApproval(id:string,status:'approved'|'rejected',actor:string,note?:string,tenantId?:string):Promise<Approval|null>{if(!['approved','rejected'].includes(status))throw new Error('Invalid approval status');if(!tenantId)throw new Error('Tenant identity is required');const item=await mutate<Approval>(files.approvals,async all=>{const item=all.find(x=>x.id===id&&x.tenantId===tenantId);if(!item)return null;if(item.status!=='pending')throw new Error('Approval is already decided');item.status=status;item.decidedBy=actor;item.note=note;item.updatedAt=now();return item;});if(!item)return null;await audit({tenantId:item.tenantId,jobId:item.jobId,candidateId:item.candidateId,action:`approval_${status}`,actor,metadata:{approvalId:id,approvalAction:item.action,note:note||''}});return item;}
export async function listApprovals(tenantId:string,jobId?:string){return(await read<Approval>(files.approvals)).filter(x=>x.tenantId===tenantId&&(!jobId||x.jobId===jobId));}
export async function listAudit(tenantId:string,jobId?:string){return(await read<AuditEvent>(files.audit)).filter(x=>x.tenantId===tenantId&&(!jobId||x.jobId===jobId));}
export async function scheduleInterview(input:Omit<InterviewSchedule,'id'|'createdAt'|'updatedAt'>):Promise<InterviewSchedule>{if(new Date(input.endsAt)<=new Date(input.startsAt))throw new Error('Interview end must be after start');const existing=await read<InterviewSchedule>(files.schedules);if(existing.find(x=>x.tenantId===input.tenantId&&x.status!=='cancelled'&&new Date(input.startsAt)<new Date(x.endsAt)&&new Date(input.endsAt)>new Date(x.startsAt)))throw new Error('Interview time overlaps an existing booking');const t=now();const value=await append(files.schedules,{...input,id:`schedule_${crypto.randomUUID()}`,createdAt:t,updatedAt:t});await audit({tenantId:input.tenantId,jobId:input.jobId,candidateId:input.candidateId,action:'interview_scheduled',actor:'system',metadata:{scheduleId:value.id,status:value.status,startsAt:value.startsAt,endsAt:value.endsAt,mode:value.mode}});return value;}
export async function updateSchedule(id:string,status:InterviewSchedule['status'],tenantId:string,actor?:string){if(!['proposed','confirmed','cancelled'].includes(status))throw new Error('Invalid schedule status');const item=await mutate<InterviewSchedule>(files.schedules,async all=>{const item=all.find(x=>x.id===id&&x.tenantId===tenantId);if(!item)return null;if(!isAllowedScheduleTransition(item.status,status))throw new Error(`Invalid interview status transition: ${item.status} -> ${status}`);const previousStatus=item.status;item.status=status;item.updatedAt=now();return {...item,__previousStatus:previousStatus} as InterviewSchedule&{__previousStatus:string};});if(!item)return null;const previousStatus=(item as InterviewSchedule&{__previousStatus?:string}).__previousStatus;delete (item as InterviewSchedule&{__previousStatus?:string}).__previousStatus;if(previousStatus!==status)await audit({tenantId:item.tenantId,jobId:item.jobId,candidateId:item.candidateId,action:'interview_status_changed',actor:actor||tenantId,metadata:{scheduleId:id,previousStatus,status}});return item;}
export async function listSchedules(tenantId:string,jobId?:string){return(await read<InterviewSchedule>(files.schedules)).filter(x=>x.tenantId===tenantId&&(!jobId||x.jobId===jobId));}
export async function recordUsage(input:UsageInput){const t=now();return append(files.usage,{...input,id:`usage_${crypto.randomUUID()}`,createdAt:t,updatedAt:t});}
export async function usageSummary(tenantId:string,period?:string){return(await read<UsageRecord>(files.usage)).filter(x=>x.tenantId===tenantId&&(!period||x.period===period)).reduce<Record<string,number>>((a,x)=>(a[x.feature]=(a[x.feature]||0)+x.units,a),{});}
export function createControlPlaneRouter(tenantId:(req:any)=>string){const r=Router();r.post('/approvals',async(req,res)=>{try{res.json(await requestApproval({...req.body,tenantId:tenantId(req)}));}catch(e:any){res.status(400).json({error:e.message})}});r.get('/approvals',async(req,res)=>res.json({approvals:await listApprovals(tenantId(req),req.query.jobId?String(req.query.jobId):undefined)}));r.post('/approvals/:id/decision',async(req,res)=>{try{const tenant=tenantId(req);const actor=String((req as any).workspaceIdentity?.email||tenant);const out=await decideApproval(String(req.params.id),req.body?.status,actor,req.body?.note,tenant);if(!out)return res.status(404).json({error:'Approval not found'});res.json(out);}catch(e:any){res.status(400).json({error:e.message})}});r.get('/audit',async(req,res)=>res.json({events:await listAudit(tenantId(req),req.query.jobId?String(req.query.jobId):undefined)}));r.post('/audit',async(req,res)=>res.json(await audit({...req.body,tenantId:tenantId(req),actor:String((req as any).workspaceIdentity?.email||tenantId(req))})));r.post('/schedules',async(req,res)=>{try{res.json(await scheduleInterview({...req.body,tenantId:tenantId(req)}));}catch(e:any){res.status(409).json({error:e.message})}});r.get('/schedules',async(req,res)=>res.json({schedules:await listSchedules(tenantId(req),req.query.jobId?String(req.query.jobId):undefined)}));r.post('/schedules/:id/status',async(req,res)=>{try{const tenant=tenantId(req);const actor=String((req as any).workspaceIdentity?.email||tenant);const out=await updateSchedule(String(req.params.id),req.body?.status,tenant,actor);if(!out)return res.status(404).json({error:'Schedule not found'});res.json(out);}catch(e:any){res.status(400).json({error:e.message})}});r.post('/usage',async(req,res)=>res.json(await recordUsage({...req.body,tenantId:tenantId(req)})));r.get('/usage',async(req,res)=>res.json({usage:await usageSummary(tenantId(req),req.query.period?String(req.query.period):undefined)}));return r;}
