import { promises as fs } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { Router } from 'express';
import { listAuditEvents, countAuditEvents, recordAuditEvent as persistAuditEvent } from './auditStore.js';
import { requirePrivilegedRecruitingRole } from './authorization.js';

type RecordBase={id:string;tenantId:string;createdAt:string;updatedAt:string};
export type Approval=RecordBase&{jobId:string;candidateId?:string;action:'jd_approval'|'reject'|'decision'|'compensation'|'offer'|'employee_create';status:'pending'|'approved'|'rejected';requestedBy:string;decidedBy?:string;note?:string};
export type AuditEvent=RecordBase&{jobId?:string;candidateId?:string;action:string;actor:string;metadata?:Record<string,unknown>;persistence:'database'|'local-fallback'};
export type InterviewSchedule=RecordBase&{jobId:string;candidateId:string;startsAt:string;endsAt:string;timezone:string;mode:'ai_audio'|'human'|'panel';status:'proposed'|'confirmed'|'cancelled';candidateEmail?:string;interviewUrl?:string};
type ScheduleStatus=InterviewSchedule['status'];
export type UsageRecord=RecordBase&{period:string;feature:string;units:number;metadata?:Record<string,unknown>};
type ApprovalInput=Omit<Approval,'id'|'createdAt'|'updatedAt'|'status'>;type AuditInput=Omit<AuditEvent,'id'|'createdAt'|'updatedAt'|'persistence'>;type UsageInput=Omit<UsageRecord,'id'|'createdAt'|'updatedAt'>;
const root=process.env.SMARTSCOUT_CONTROL_PLANE_DIR||path.join(process.cwd(),'.smartscout-control-plane');const files={approvals:'approvals.json',audit:'audit.json',schedules:'schedules.json',usage:'usage.json'} as const;const queues:Record<string,Promise<void>>={};
async function read<T>(name:string):Promise<T[]>{try{return JSON.parse(await fs.readFile(path.join(root,name),'utf8'));}catch{return[];}}
async function append<T extends RecordBase>(name:string,value:T):Promise<T>{await fs.mkdir(root,{recursive:true});const prior=queues[name]||Promise.resolve();const operation=prior.then(async()=>{const all=await read<T>(name);all.unshift(value);await fs.writeFile(path.join(root,name),JSON.stringify(all.slice(0,10000),null,2),'utf8');});queues[name]=operation.catch(()=>{});await operation;return value;}
async function mutate<T>(name:string, fn:(all:T[])=>Promise<T>|T):Promise<T>{await fs.mkdir(root,{recursive:true});const prior=queues[name]||Promise.resolve();let result!:T;const operation=prior.then(async()=>{const all=await read<T>(name);result=await fn(all);await fs.writeFile(path.join(root,name),JSON.stringify(all,null,2),'utf8');});queues[name]=operation.catch(()=>{});await operation;return result;}
const now=()=>new Date().toISOString();
const requiredIdentity=(value:string,name:string)=>{const normalized=String(value??'').trim();if(!normalized)throw new Error(`${name} is required`);if(normalized.length>256)throw new Error(`${name} is too long`);return normalized;};
const allowedScheduleTransitions:Record<ScheduleStatus,readonly ScheduleStatus[]>={proposed:['proposed','confirmed','cancelled'],confirmed:['confirmed','cancelled'],cancelled:['cancelled']};
export function isAllowedScheduleTransition(from:ScheduleStatus,to:ScheduleStatus){return allowedScheduleTransitions[from].includes(to);}
export function isValidInterviewWindow(startsAt:string,endsAt:string){const start=Date.parse(startsAt);const end=Date.parse(endsAt);return Number.isFinite(start)&&Number.isFinite(end)&&end>start;}
const validateScheduleState=(status:InterviewSchedule['status'],mode:InterviewSchedule['mode'])=>{if(!['proposed','confirmed','cancelled'].includes(status))throw new Error('Invalid schedule status');if(!['ai_audio','human','panel'].includes(mode))throw new Error('Invalid interview mode');return {status,mode};};
export async function audit(input:AuditInput):Promise<AuditEvent>{const tenantId=requiredIdentity(input.tenantId,'Tenant identity');const actor=requiredIdentity(input.actor,'Audit actor');const action=requiredIdentity(input.action,'Audit action');const t=now();const persisted=await persistAuditEvent({tenantId,workflowId:input.jobId||null,candidateId:input.candidateId||null,eventType:action,actorType:actor,actorId:actor,payload:input.metadata||{}});const persistence:AuditEvent['persistence']=persisted.persisted?'database':'local-fallback';const value={...input,tenantId,actor,action,id:`audit_${crypto.randomUUID()}`,createdAt:t,updatedAt:t,persistence};if(!persisted.persisted)await append(files.audit,value);return value;}
export async function requestApproval(input:ApprovalInput):Promise<Approval>{const tenantId=requiredIdentity(input.tenantId,'Tenant identity');const jobId=requiredIdentity(input.jobId,'Job identity');const requestedBy=requiredIdentity(input.requestedBy,'Requester identity');const t=now();const value:Approval={...input,tenantId,jobId,requestedBy,id:`approval_${crypto.randomUUID()}`,createdAt:t,updatedAt:t,status:'pending'};await append(files.approvals,value);await audit({tenantId,jobId,candidateId:input.candidateId,action:'approval_requested',actor:requestedBy,metadata:{approvalId:value.id,approvalAction:value.action}});return value;}
export async function decideApproval(id:string,status:'approved'|'rejected',actor:string,note?:string,tenantId?:string):Promise<Approval|null>{if(!['approved','rejected'].includes(status))throw new Error('Invalid approval status');const tenant=requiredIdentity(tenantId||'','Tenant identity');const decisionActor=requiredIdentity(actor,'Decision actor');const approvalId=requiredIdentity(id,'Approval identity');const item=await mutate<Approval>(files.approvals,async all=>{const item=all.find(x=>x.id===approvalId&&x.tenantId===tenant);if(!item)return null;if(item.status!=='pending')throw new Error('Approval is already decided');item.status=status;item.decidedBy=decisionActor;item.note=note;item.updatedAt=now();return item;});if(!item)return null;await audit({tenantId:item.tenantId,jobId:item.jobId,candidateId:item.candidateId,action:`approval_${status}`,actor:decisionActor,metadata:{approvalId,note:note||''}});return item;}
export async function listApprovals(tenantId:string,jobId?:string){const tenant=requiredIdentity(tenantId,'Tenant identity');return(await read<Approval>(files.approvals)).filter(x=>x.tenantId===tenant&&(!jobId||x.jobId===jobId));}
function auditDatabaseConfigured(){return Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY);}
function mapDatabaseAuditEvent(event:any):AuditEvent{const createdAt=String(event.created_at||now());return{id:`audit_${event.id}`,tenantId:String(event.tenant_id),jobId:event.workflow_id?`job_${event.workflow_id}`:undefined,candidateId:event.candidate_id?`candidate_${event.candidate_id}`:undefined,action:String(event.event_type),actor:String(event.actor_id||event.actor_type||'system'),metadata:event.payload&&typeof event.payload==='object'?event.payload:undefined,createdAt,updatedAt:createdAt,persistence:'database'};}
export async function listAudit(tenantId:string,jobId?:string,candidateId?:string){const tenant=requiredIdentity(tenantId,'Tenant identity');const normalizedJobId=jobId===undefined?undefined:requiredIdentity(jobId,'Job identity');const normalizedCandidateId=candidateId===undefined?undefined:requiredIdentity(candidateId,'Candidate identity');if(auditDatabaseConfigured()){const events=await listAuditEvents(tenant,normalizedJobId,normalizedCandidateId);return events.map(mapDatabaseAuditEvent);}return(await read<AuditEvent>(files.audit)).filter(x=>x.tenantId===tenant&&(!normalizedJobId||x.jobId===normalizedJobId)&&(!normalizedCandidateId||x.candidateId===normalizedCandidateId));}
export async function countAudit(tenantId:string,jobId?:string,candidateId?:string){const tenant=requiredIdentity(tenantId,'Tenant identity');const normalizedJobId=jobId===undefined?undefined:requiredIdentity(jobId,'Job identity');const normalizedCandidateId=candidateId===undefined?undefined:requiredIdentity(candidateId,'Candidate identity');if(auditDatabaseConfigured())return countAuditEvents(tenant,normalizedJobId,normalizedCandidateId);return{configured:false,count:(await read<AuditEvent>(files.audit)).filter(x=>x.tenantId===tenant&&(!normalizedJobId||x.jobId===jobId)&&(!normalizedCandidateId||x.candidateId===candidateId)).length};}
export async function scheduleInterview(input:Omit<InterviewSchedule,'id'|'createdAt'|'updatedAt'>,actor='system'):Promise<InterviewSchedule>{const tenantId=requiredIdentity(input.tenantId,'Tenant identity');const jobId=requiredIdentity(input.jobId,'Job identity');const candidateId=requiredIdentity(input.candidateId,'Candidate identity');const timezone=requiredIdentity(input.timezone,'Interview timezone');const auditActor=requiredIdentity(actor,'Interview actor');validateScheduleState(input.status,input.mode);if(!isValidInterviewWindow(input.startsAt,input.endsAt))throw new Error('Interview window must contain valid timestamps with end after start');const t=now();const value=await mutate<InterviewSchedule>(files.schedules,all=>{if(all.find(x=>x.tenantId===tenantId&&x.status!=='cancelled'&&new Date(input.startsAt)<new Date(x.endsAt)&&new Date(input.endsAt)>new Date(x.startsAt)))throw new Error('Interview time overlaps an existing booking');return {...input,tenantId,jobId,candidateId,timezone,id:`schedule_${crypto.randomUUID()}`,createdAt:t,updatedAt:t};});await audit({tenantId,jobId,candidateId,action:'interview_scheduled',actor:auditActor,metadata:{scheduleId:value.id,status:value.status,startsAt:value.startsAt,endsAt:value.endsAt,mode:value.mode}});return value;}
export async function updateSchedule(id:string,status:InterviewSchedule['status'],tenantId:string,actor?:string){if(!['proposed','confirmed','cancelled'].includes(status))throw new Error('Invalid schedule status');const tenant=requiredIdentity(tenantId,'Tenant identity');const auditActor=requiredIdentity(actor||tenant,'Interview actor');const scheduleId=requiredIdentity(id,'Schedule identity');let previousStatus:ScheduleStatus|undefined;const item=await mutate<InterviewSchedule>(files.schedules,async all=>{const item=all.find(x=>x.id===scheduleId&&x.tenantId===tenant);if(!item)return null;if(!isAllowedScheduleTransition(item.status,status))throw new Error(`Invalid interview status transition: ${item.status} -> ${status}`);if(status==='confirmed'){const overlaps=all.some(x=>x.id!==item.id&&x.tenantId===tenant&&x.status!=='cancelled'&&new Date(item.startsAt)<new Date(x.endsAt)&&new Date(item.endsAt)>new Date(x.startsAt));if(overlaps)throw new Error('Interview time overlaps an existing booking');}previousStatus=item.status;item.status=status;item.updatedAt=now();return item;});if(!item)return null;if(previousStatus!==status)await audit({tenantId:item.tenantId,jobId:item.jobId,candidateId:item.candidateId,action:'interview_status_changed',actor:auditActor,metadata:{scheduleId,previousStatus,status}});return item;}
export async function listSchedules(tenantId:string,jobId?:string){const tenant=requiredIdentity(tenantId,'Tenant identity');return(await read<InterviewSchedule>(files.schedules)).filter(x=>x.tenantId===tenant&&(!jobId||x.jobId===jobId));}
export async function recordUsage(input:UsageInput,actor='system'){const tenantId=requiredIdentity(input.tenantId,'Tenant identity');const feature=requiredIdentity(input.feature,'Usage feature');const auditActor=requiredIdentity(actor,'Usage actor');const t=now();const value=await append(files.usage,{...input,tenantId,feature,id:`usage_${crypto.randomUUID()}`,createdAt:t,updatedAt:t});await audit({tenantId,action:'usage_recorded',actor:auditActor,metadata:{usageId:value.id,period:value.period,feature:value.feature,units:value.units}});return value;}
export async function usageSummary(tenantId:string,period?:string){const tenant=requiredIdentity(tenantId,'Tenant identity');return(await read<UsageRecord>(files.usage)).filter(x=>x.tenantId===tenant&&(!period||x.period===period)).reduce<Record<string,number>>((a,x)=>(a[x.feature]=(a[x.feature]||0)+x.units,a),{});}
export function createControlPlaneRouter(tenantId:(req:any)=>string){const r=Router();const resolveTenant=(req:any)=>requiredIdentity(tenantId(req),'Tenant identity');const actorFromRequest=(req:any)=>requiredIdentity(String((req as any).workspaceIdentity?.email||(req as any).workspaceIdentity?.id||''),'Authenticated actor');const requireRecruitingRole=(req:any)=>requirePrivilegedRecruitingRole((req as any).workspaceIdentity?.role);
r.post('/approvals',async(req,res)=>{try{const tenant=resolveTenant(req);const actor=actorFromRequest(req);requireRecruitingRole(req);res.json(await requestApproval({...req.body,tenantId:tenant,requestedBy:actor}));}catch(e:any){const forbidden=e?.message==='Insufficient permissions';res.status(forbidden?403:400).json({error:forbidden?'Insufficient permissions':e.message})}});
r.get('/approvals',async(req,res)=>res.json({approvals:await listApprovals(resolveTenant(req),req.query.jobId?String(req.query.jobId):undefined)}));
r.post('/approvals/:id/decision',async(req,res)=>{try{const tenant=resolveTenant(req);const actor=actorFromRequest(req);requireRecruitingRole(req);const out=await decideApproval(String(req.params.id),req.body?.status,actor,req.body?.note,tenant);if(!out)return res.status(404).json({error:'Approval not found'});res.json(out);}catch(e:any){const forbidden=e?.message==='Insufficient permissions';res.status(forbidden?403:400).json({error:forbidden?'Insufficient permissions':e.message})}});
r.get('/audit',async(req,res)=>res.json({events:await listAudit(resolveTenant(req),req.query.jobId?String(req.query.jobId):undefined,req.query.candidateId?String(req.query.candidateId):undefined)}));r.get('/audit/count',async(req,res)=>res.json(await countAudit(resolveTenant(req),req.query.jobId?String(req.query.jobId):undefined,req.query.candidateId?String(req.query.candidateId):undefined)));r.post('/audit',async(req,res)=>{try{const tenant=resolveTenant(req);const actor=actorFromRequest(req);requireRecruitingRole(req);res.json(await audit({...req.body,tenantId:tenant,actor}));}catch(e:any){const forbidden=e?.message==='Insufficient permissions';res.status(forbidden?403:400).json({error:forbidden?'Insufficient permissions':e.message})}});
r.post('/schedules',async(req,res)=>{try{const tenant=resolveTenant(req);const actor=actorFromRequest(req);requireRecruitingRole(req);res.json(await scheduleInterview({...req.body,tenantId:tenant},actor));}catch(e:any){const forbidden=e?.message==='Insufficient permissions';res.status(forbidden?403:409).json({error:forbidden?'Insufficient permissions':e.message})}});
r.get('/schedules',async(req,res)=>res.json({schedules:await listSchedules(resolveTenant(req),req.query.jobId?String(req.query.jobId):undefined)}));
r.post('/schedules/:id/status',async(req,res)=>{try{const tenant=resolveTenant(req);const actor=actorFromRequest(req);requireRecruitingRole(req);const out=await updateSchedule(String(req.params.id),req.body?.status,tenant,actor);if(!out)return res.status(404).json({error:'Schedule not found'});res.json(out);}catch(e:any){const forbidden=e?.message==='Insufficient permissions';res.status(forbidden?403:400).json({error:forbidden?'Insufficient permissions':e.message})}});
r.post('/usage',async(req,res)=>{try{const tenant=resolveTenant(req);const actor=actorFromRequest(req);requireRecruitingRole(req);res.json(await recordUsage({...req.body,tenantId:tenant},actor));}catch(e:any){const forbidden=e?.message==='Insufficient permissions';res.status(forbidden?403:400).json({error:forbidden?'Insufficient permissions':e.message})}});
r.get('/usage',async(req,res)=>res.json({usage:await usageSummary(resolveTenant(req),req.query.period?String(req.query.period):undefined)}));return r;}